# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import structlog
from fastapi import APIRouter

from os2mo_rollekatalog import depends
from os2mo_rollekatalog.autogenerated_graphql_client import (
    GetTitlesClassesObjectsCurrent,
)
from os2mo_rollekatalog.titles import get_job_titles

router = APIRouter()
logger = structlog.get_logger(__name__)


@router.get("/hello")
async def hello() -> str:
    """Greetings."""
    return "World!"


@router.get("/titles")
async def titles(mo: depends.GraphQLClient) -> list[GetTitlesClassesObjectsCurrent]:
    """Get job titles that will be synced."""
    return await get_job_titles(mo)
