# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import structlog
from fastapi import APIRouter
from uuid import UUID

from os2mo_rollekatalog import depends
from os2mo_rollekatalog.autogenerated_graphql_client import (
    GetTitlesClassesObjectsCurrent,
)
from os2mo_rollekatalog.models import User
from os2mo_rollekatalog.person import get_person
from os2mo_rollekatalog.titles import get_job_titles


router = APIRouter()
logger = structlog.get_logger(__name__)


@router.get("/hello")
async def hello() -> str:
    """Greetings."""
    return "World!"


@router.get("/titles")
async def titles(mo: depends.GraphQLClient) -> list[GetTitlesClassesObjectsCurrent]:
    """Get job titles that will be synced."""
    return await get_job_titles(mo)


@router.get("/person")
async def person(
    settings: depends.Settings, mo: depends.GraphQLClient, person_uuid: UUID
) -> User | None:
    """See how a person will be synced."""
    return await get_person(
        mo,
        settings.itsystem_user_key,
        person_uuid,
        settings.use_nickname,
        settings.sync_titles,
    )
