# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from typing import Annotated

from fastapi import Depends
from fastramqpi.depends import from_user_context
from fastramqpi.ramqp.depends import from_context
from httpx import AsyncClient

from os2mo_rollekatalog import models
from os2mo_rollekatalog import rollekatalog
from os2mo_rollekatalog.autogenerated_graphql_client import (
    GraphQLClient as _GraphQLClient,
)
from os2mo_rollekatalog.config import _Settings

GraphQLClient = Annotated[_GraphQLClient, Depends(from_context("graphql_client"))]
Settings = Annotated[_Settings, Depends(from_user_context("settings"))]
TitleClient = Annotated[AsyncClient, Depends(from_user_context("title_client"))]
OrgUnitCache = Annotated[
    models.OrgUnitCache, Depends(from_user_context("org_unit_cache"))
]
UserCache = Annotated[models.UserCache, Depends(from_user_context("user_cache"))]
Rollekatalog = Annotated[
    rollekatalog.Rollekatalog, Depends(from_user_context("rollekatalog"))
]
