# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from typing import Annotated

from fastapi import Depends
from fastramqpi.depends import from_user_context
from fastramqpi.ramqp.depends import from_context
from os2mo_rollekatalog.autogenerated_graphql_client import (
    GraphQLClient as _GraphQLClient,
)
from os2mo_rollekatalog.config import _Settings

GraphQLClient = Annotated[_GraphQLClient, Depends(from_context("graphql_client"))]
Settings = Annotated[_Settings, Depends(from_user_context("settings"))]
UserCache = Annotated[dict, Depends(from_user_context("user_cache"))]
OrgUnitCache = Annotated[dict, Depends(from_user_context("org_unit_cache"))]
