# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from uuid import UUID

from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient
from os2mo_rollekatalog.models import Function


async def get_functions(
    mo: GraphQLClient, association_type_uuids: list[UUID] | None
) -> list[Function]:
    mo_functions = await mo.get_functions(association_type_uuids)
    functions = [
        Function(uuid=obj.current.uuid, name=obj.current.name)
        for obj in mo_functions.objects
        if obj.current is not None
    ]
    return functions
