# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from uuid import UUID

import structlog
from httpx import AsyncClient
from httpx import HTTPStatusError
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient
from os2mo_rollekatalog.models import Function


logger = structlog.stdlib.get_logger(__name__)


async def get_function_types(mo: GraphQLClient) -> dict[UUID, str]:
    mo_functions = await mo.get_functions()
    return {
        obj.current.uuid: obj.current.name
        for obj in mo_functions.objects
        if obj.current is not None
    }


async def fetch_function_map(session: AsyncSession) -> dict[UUID, UUID]:
    functions = (await session.scalars(select(Function))).all()
    return {f.mo_uuid: f.rk_uuid for f in functions if f.rk_uuid is not None}


async def sync_function_catalog(
    mo: GraphQLClient,
    client: AsyncClient,
    session: AsyncSession,
) -> bool:
    """Sync MO's association types to Rollekatalog's function catalog.

    Rollekatalog looks functions up by the UUID we send, falling back to the
    name, and generates its own UUID when a function is created. Sending the
    remembered rk_uuid together with the current MO name is what makes a
    rename in MO a rename in Rollekatalog instead of a delete + create, which
    would orphan the roles configured on the function.

    Returns whether anything changed, so the caller can schedule an
    organisation sync.
    """
    mo_functions = await get_function_types(mo)
    db_functions = (await session.scalars(select(Function))).all()
    db_by_mo = {f.mo_uuid: f for f in db_functions}

    changed = False
    for mo_uuid, name in mo_functions.items():
        existing = db_by_mo.get(mo_uuid)
        if existing is None:
            session.add(Function(mo_uuid=mo_uuid, rk_uuid=None, name=name))
            logger.info("Add function", uuid=mo_uuid, name=name)
            changed = True
        elif existing.name != name:
            logger.info("Rename function", uuid=mo_uuid, old=existing.name, new=name)
            existing.name = name
            changed = True
    for mo_uuid, function in db_by_mo.items():
        if mo_uuid not in mo_functions:
            await session.delete(function)
            logger.info("Remove function", uuid=mo_uuid, name=function.name)
            changed = True
    await session.flush()

    db_functions = (await session.scalars(select(Function))).all()
    if not db_functions:
        # Rollekatalog rejects an empty payload, so functions deactivated in
        # MO can only be deactivated in Rollekatalog while at least one is
        # left.
        return changed

    payload = [
        {"name": f.name} | ({"uuid": str(f.rk_uuid)} if f.rk_uuid else {})
        for f in db_functions
    ]
    logger.info("Uploading functions to Rollekatalog", payload=payload)
    try:
        r = await client.post("/api/v2/function/sync", json=payload)
        r.raise_for_status()
    except HTTPStatusError as e:
        logger.error("Error: Failed to upload functions", http_body=e.response.text)
        raise e

    # Remember Rollekatalog's UUIDs. With sync disabled, the mocked response
    # is empty and the known mapping is left untouched.
    rk_uuid_by_name = {f["name"]: UUID(f["uuid"]) for f in r.json()}
    for function in db_functions:
        rk_uuid = rk_uuid_by_name.get(function.name, function.rk_uuid)
        if function.rk_uuid != rk_uuid:
            function.rk_uuid = rk_uuid
            changed = True
    return changed
