# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from os2mo_rollekatalog.autogenerated_graphql_client import (
    GetTitlesClassesObjectsCurrent,
)
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient


async def get_job_titles(mo: GraphQLClient) -> list[GetTitlesClassesObjectsCurrent]:
    mo_titles = await mo.get_titles()
    titles = [obj.current for obj in mo_titles.objects if obj.current is not None]
    return titles
