# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient
from os2mo_rollekatalog.models import Title


async def get_job_titles(mo: GraphQLClient) -> list[Title]:
    mo_titles = await mo.get_titles()
    titles = [
        Title(uuid=obj.current.uuid, user_key=obj.current.user_key)
        for obj in mo_titles.objects
        if obj.current is not None
    ]
    return titles
