# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from collections.abc import AsyncIterator
from collections.abc import Awaitable
from collections.abc import Callable
from uuid import uuid4
from uuid import UUID

import pytest
from fastapi import FastAPI
from fastapi.encoders import jsonable_encoder
from fastramqpi.events import Event
from httpx import AsyncClient
from pytest import MonkeyPatch

from os2mo_rollekatalog.app import create_app
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient


@pytest.fixture
def root_uuid():
    return uuid4()


@pytest.fixture
def exclude_org_unit_level():
    return uuid4()


@pytest.fixture
def external_roots():
    return [str(uuid4())]


@pytest.fixture
async def app(
    monkeypatch: MonkeyPatch,
    root_uuid: UUID,
    exclude_org_unit_level: UUID,
    external_roots: list[UUID],
) -> FastAPI:
    monkeypatch.setenv("ROLLEKATALOG_URL", "http://example.org")
    monkeypatch.setenv("API_KEY", "dummy")
    monkeypatch.setenv("ROOT_ORG_UNIT", str(root_uuid))
    monkeypatch.setenv("SYNC_TITLES", "false")
    monkeypatch.setenv(
        "AD_ITSYSTEM_USER_KEYS", json.dumps(["Active Directory", "Skole-AD"])
    )
    monkeypatch.setenv("FK_ITSYSTEM_USER_KEY", "FK ORG")
    monkeypatch.setenv(
        "EXCLUDE_ORG_UNIT_LEVELS", json.dumps([str(exclude_org_unit_level)])
    )
    monkeypatch.setenv("EXTERNAL_ROOTS", json.dumps(external_roots))

    return create_app()


@pytest.fixture
async def graphql_client(mo_client: AsyncClient) -> AsyncIterator[GraphQLClient]:
    """Authenticated GraphQL codegen client for OS2mo."""
    graphql_client = GraphQLClient(
        url=f"{mo_client.base_url}/graphql/v25",
        http_client=mo_client,
    )
    async with graphql_client as client:
        yield client


async def _create_facet(graphql_client: GraphQLClient, user_key: str) -> UUID:
    return (await graphql_client._testing__create_facet(user_key)).uuid


async def _create_class(
    graphql_client: GraphQLClient,
    facet_user_key: str,
    name: str,
    scope: str | None = None,
) -> UUID:
    facet = await _create_facet(graphql_client, facet_user_key)
    r = await graphql_client._testing__create_class(
        name=name, facet_uuid=facet, scope=scope
    )
    return r.uuid


@pytest.fixture
async def org_unit_type_facet(graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "org_unit_type")


@pytest.fixture
async def org_unit_type(
    graphql_client: GraphQLClient, org_unit_type_facet: UUID
) -> UUID:
    r = await graphql_client._testing__create_class(
        name="Afdeling", facet_uuid=org_unit_type_facet
    )
    return r.uuid


@pytest.fixture
async def org_unit_level_facet(graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "org_unit_level")


@pytest.fixture
async def engagement_type(graphql_client: GraphQLClient) -> UUID:
    return await _create_class(graphql_client, "engagement_type", "Ansat")


@pytest.fixture
async def job_function(graphql_client: GraphQLClient) -> UUID:
    return await _create_class(graphql_client, "engagement_job_function", "Jurist")


@pytest.fixture
async def manager_level(graphql_client: GraphQLClient) -> UUID:
    return await _create_class(graphql_client, "manager_level", "Niveau 1")


@pytest.fixture
async def manager_type(graphql_client: GraphQLClient) -> UUID:
    return await _create_class(graphql_client, "manager_type", "Leder")


@pytest.fixture
async def responsibility(graphql_client: GraphQLClient) -> UUID:
    return await _create_class(graphql_client, "responsibility", "MUS")


@pytest.fixture
async def employee_address_type_facet(graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "employee_address_type")


@pytest.fixture
async def email_address_type(
    graphql_client: GraphQLClient, employee_address_type_facet: UUID
) -> UUID:
    r = await graphql_client._testing__create_class(
        name="EmailEmployee",
        facet_uuid=employee_address_type_facet,
        scope="EMAIL",
    )
    return r.uuid


@pytest.fixture
async def mit_id_address_type(
    graphql_client: GraphQLClient, employee_address_type_facet: UUID
) -> UUID:
    r = await graphql_client._testing__create_class(
        name="MitIDEmployee",
        facet_uuid=employee_address_type_facet,
        scope="TEXT",
    )
    return r.uuid


@pytest.fixture
def trigger_event(
    test_client: AsyncClient,
) -> Callable[[str, UUID], Awaitable[None]]:
    """Return a callable that POSTs a GraphQL event to a listener endpoint.

    Drives a handler the same way FastRAMQPI's event system does — over its
    external HTTP interface — so the handler runs synchronously.
    """

    async def inner(routing_key: str, subject: UUID) -> None:
        r = await test_client.post(
            f"/{routing_key}",
            json=jsonable_encoder(Event(subject=subject, priority=1)),
        )
        r.raise_for_status()

    return inner
