# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from collections.abc import AsyncIterator
from uuid import uuid4
from uuid import UUID

import pytest
from fastapi import FastAPI
from httpx import AsyncClient
from pytest import MonkeyPatch

from os2mo_rollekatalog.app import create_app
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient


@pytest.fixture
def root_uuid():
    return uuid4()


@pytest.fixture
def exclude_org_unit_level():
    return uuid4()


@pytest.fixture
def external_roots():
    return [str(uuid4())]


@pytest.fixture
async def app(
    monkeypatch: MonkeyPatch,
    root_uuid: UUID,
    exclude_org_unit_level: UUID,
    external_roots: list[UUID],
) -> FastAPI:
    monkeypatch.setenv("ROLLEKATALOG_URL", "http://example.org")
    monkeypatch.setenv("API_KEY", "dummy")
    monkeypatch.setenv("ROOT_ORG_UNIT", str(root_uuid))
    monkeypatch.setenv("SYNC_TITLES", "false")
    monkeypatch.setenv("AD_ITSYSTEM_USER_KEY", "Active Directory")
    monkeypatch.setenv("FK_ITSYSTEM_USER_KEY", "FK ORG")
    monkeypatch.setenv("EXCLUDE_ORG_UNIT_LEVEL", str(exclude_org_unit_level))
    monkeypatch.setenv("EXTERNAL_ROOTS", json.dumps(external_roots))

    return create_app()


@pytest.fixture
async def graphql_client(mo_client: AsyncClient) -> AsyncIterator[GraphQLClient]:
    """Authenticated GraphQL codegen client for OS2mo."""
    graphql_client = GraphQLClient(
        url=f"{mo_client.base_url}/graphql/v25",
        http_client=mo_client,
    )
    async with graphql_client as client:
        yield client
