# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from collections.abc import AsyncIterator
from collections.abc import Awaitable
from collections.abc import Callable
from datetime import datetime
from datetime import timezone
from uuid import uuid4
from uuid import UUID

import pytest
from fastapi import FastAPI
from fastapi.encoders import jsonable_encoder
from fastramqpi.events import Event
from httpx import AsyncClient
from pytest import MonkeyPatch

from os2mo_rollekatalog.app import create_app
from os2mo_rollekatalog.app import GRAPHQL_VERSION
from os2mo_rollekatalog.autogenerated_graphql_client import AddressCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import ClassCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import EngagementCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import FacetCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient
from os2mo_rollekatalog.autogenerated_graphql_client import ITSystemCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import ITUserCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import ManagerCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import OrganisationUnitCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import RAOpenValidityInput
from os2mo_rollekatalog.autogenerated_graphql_client import RAValidityInput
from os2mo_rollekatalog.autogenerated_graphql_client import ValidityInput

SEED_FROM = datetime(1930, 1, 1, tzinfo=timezone.utc)
SEED_VALIDITY = ValidityInput(from_=SEED_FROM)
SEED_RA_VALIDITY = RAValidityInput(from_=SEED_FROM)
SEED_OPEN_VALIDITY = RAOpenValidityInput(from_=SEED_FROM)


@pytest.fixture
def root_uuid() -> UUID:
    return uuid4()


@pytest.fixture
def exclude_org_unit_level() -> UUID:
    return uuid4()


@pytest.fixture
def external_roots() -> list[UUID]:
    return [uuid4()]


@pytest.fixture
async def app(
    monkeypatch: MonkeyPatch,
    root_uuid: UUID,
    exclude_org_unit_level: UUID,
    external_roots: list[UUID],
) -> FastAPI:
    monkeypatch.setenv("ROLLEKATALOG_URL", "http://example.org")
    monkeypatch.setenv("API_KEY", "dummy")
    monkeypatch.setenv("ROOT_ORG_UNIT", str(root_uuid))
    monkeypatch.setenv("SYNC_TITLES", "false")
    monkeypatch.setenv(
        "AD_ITSYSTEM_USER_KEYS", json.dumps(["Active Directory", "Skole-AD"])
    )
    monkeypatch.setenv("FK_ITSYSTEM_USER_KEY", "FK ORG")
    monkeypatch.setenv("EXCLUDE_ORG_UNIT_LEVEL", str(exclude_org_unit_level))
    monkeypatch.setenv(
        "EXTERNAL_ROOTS", json.dumps([str(root) for root in external_roots])
    )

    return create_app()


@pytest.fixture
async def graphql_client(mo_client: AsyncClient) -> AsyncIterator[GraphQLClient]:
    """Authenticated GraphQL codegen client for OS2mo."""
    graphql_client = GraphQLClient(
        url=f"{mo_client.base_url}/graphql/v{GRAPHQL_VERSION}",
        http_client=mo_client,
    )
    async with graphql_client as client:
        yield client


# --- Facet fixtures ---


async def _create_facet(graphql_client: GraphQLClient, user_key: str) -> UUID:
    r = await graphql_client._testing__create_facet(
        input=FacetCreateInput(user_key=user_key, validity=SEED_VALIDITY)
    )
    return r.uuid


@pytest.fixture
async def org_unit_type_facet(graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "org_unit_type")


@pytest.fixture
async def org_unit_level_facet(graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "org_unit_level")


@pytest.fixture
async def engagement_type_facet(graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "engagement_type")


@pytest.fixture
async def engagement_job_function_facet(graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "engagement_job_function")


@pytest.fixture
async def manager_level_facet(graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "manager_level")


@pytest.fixture
async def manager_type_facet(graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "manager_type")


@pytest.fixture
async def responsibility_facet(graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "responsibility")


@pytest.fixture
async def employee_address_type_facet(graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "employee_address_type")


# --- Class fixtures ---


async def _create_class(
    graphql_client: GraphQLClient,
    facet_uuid: UUID,
    name: str,
    scope: str | None = None,
) -> UUID:
    r = await graphql_client._testing__create_class(
        input=ClassCreateInput(
            user_key=name,
            name=name,
            facet_uuid=facet_uuid,
            scope=scope,
            validity=SEED_VALIDITY,
        )
    )
    return r.uuid


@pytest.fixture
async def afdeling(graphql_client: GraphQLClient, org_unit_type_facet: UUID) -> UUID:
    return await _create_class(graphql_client, org_unit_type_facet, "Afdeling")


@pytest.fixture
async def ansat(graphql_client: GraphQLClient, engagement_type_facet: UUID) -> UUID:
    return await _create_class(graphql_client, engagement_type_facet, "Ansat")


@pytest.fixture
async def jurist(
    graphql_client: GraphQLClient, engagement_job_function_facet: UUID
) -> UUID:
    return await _create_class(graphql_client, engagement_job_function_facet, "Jurist")


@pytest.fixture
async def niveau1(graphql_client: GraphQLClient, manager_level_facet: UUID) -> UUID:
    return await _create_class(graphql_client, manager_level_facet, "Niveau 1")


@pytest.fixture
async def leder(graphql_client: GraphQLClient, manager_type_facet: UUID) -> UUID:
    return await _create_class(graphql_client, manager_type_facet, "Leder")


@pytest.fixture
async def mus(graphql_client: GraphQLClient, responsibility_facet: UUID) -> UUID:
    return await _create_class(graphql_client, responsibility_facet, "MUS")


@pytest.fixture
async def email_employee(
    graphql_client: GraphQLClient, employee_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, employee_address_type_facet, "EmailEmployee", "EMAIL"
    )


@pytest.fixture
async def mit_id_employee(
    graphql_client: GraphQLClient, employee_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, employee_address_type_facet, "MitIDEmployee", "TEXT"
    )


# --- Object factory fixtures ---
#
# Factories hide the MO-required fields the tests never care about (org units
# hide `org_unit_type`; engagements hide type and job function; managers hide
# level/type/responsibility), so tests read as e.g.
# `create_manager(person=..., org_unit=...)` without the noise. Validity is
# defaulted rather than hidden: everything starts at SEED_FROM unless a test
# passes `from_`, which the tests about future validities do. Employees are
# created inline in the tests, since their fields are the data under test.


@pytest.fixture
def create_org_unit(
    graphql_client: GraphQLClient, afdeling: UUID
) -> Callable[..., Awaitable[UUID]]:
    async def inner(
        name: str,
        parent: UUID | None = None,
        uuid: UUID | None = None,
        org_unit_level: UUID | None = None,
    ) -> UUID:
        r = await graphql_client._testing__create_org_unit(
            input=OrganisationUnitCreateInput(
                uuid=uuid,
                name=name,
                parent=parent,
                org_unit_type=afdeling,
                org_unit_level=org_unit_level,
                validity=SEED_RA_VALIDITY,
            )
        )
        return r.uuid

    return inner


@pytest.fixture
def create_it_system(
    graphql_client: GraphQLClient,
) -> Callable[..., Awaitable[UUID]]:
    async def inner(user_key: str) -> UUID:
        r = await graphql_client._testing__create_it_system(
            input=ITSystemCreateInput(
                user_key=user_key,
                name=user_key,
                validity=SEED_OPEN_VALIDITY,
            )
        )
        return r.uuid

    return inner


@pytest.fixture
def create_ituser(
    graphql_client: GraphQLClient,
) -> Callable[..., Awaitable[UUID]]:
    async def inner(
        itsystem: UUID,
        external_id: str,
        person: UUID,
        user_key: str,
        engagements: list[UUID] | None = None,
        uuid: UUID | None = None,
        from_: datetime = SEED_FROM,
    ) -> UUID:
        r = await graphql_client._testing__create_it_user(
            input=ITUserCreateInput(
                uuid=uuid,
                user_key=user_key,
                external_id=external_id,
                itsystem=itsystem,
                person=person,
                engagements=engagements,
                validity=RAValidityInput(from_=from_),
            )
        )
        return r.uuid

    return inner


@pytest.fixture
def create_engagement(
    graphql_client: GraphQLClient, ansat: UUID, jurist: UUID
) -> Callable[..., Awaitable[UUID]]:
    """Positions created here are named "Jurist" (the `jurist` fixture)."""

    async def inner(org_unit: UUID, person: UUID, from_: datetime = SEED_FROM) -> UUID:
        r = await graphql_client._testing__create_engagement(
            input=EngagementCreateInput(
                org_unit=org_unit,
                person=person,
                engagement_type=ansat,
                job_function=jurist,
                validity=RAValidityInput(from_=from_),
            )
        )
        return r.uuid

    return inner


@pytest.fixture
def create_manager(
    graphql_client: GraphQLClient,
    niveau1: UUID,
    leder: UUID,
    mus: UUID,
) -> Callable[..., Awaitable[UUID]]:
    async def inner(
        person: UUID,
        org_unit: UUID,
        from_: datetime = SEED_FROM,
        to: datetime | None = None,
    ) -> UUID:
        r = await graphql_client._testing__create_manager(
            input=ManagerCreateInput(
                person=person,
                org_unit=org_unit,
                manager_level=niveau1,
                manager_type=leder,
                responsibility=[mus],
                validity=RAValidityInput(from_=from_, to=to),
            )
        )
        return r.uuid

    return inner


@pytest.fixture
def create_address(
    graphql_client: GraphQLClient,
) -> Callable[..., Awaitable[UUID]]:
    async def inner(
        person: UUID,
        value: str,
        address_type: UUID,
        ituser: UUID | None = None,
        from_: datetime = SEED_FROM,
    ) -> UUID:
        r = await graphql_client._testing__create_address(
            input=AddressCreateInput(
                person=person,
                value=value,
                address_type=address_type,
                ituser=ituser,
                validity=RAValidityInput(from_=from_),
            )
        )
        return r.uuid

    return inner


@pytest.fixture
def trigger_event(
    test_client: AsyncClient,
) -> Callable[[str, UUID], Awaitable[None]]:
    """Return a callable that POSTs a GraphQL event to a listener endpoint.

    Drives a handler the same way FastRAMQPI's event system does — over its
    external HTTP interface — so the handler runs synchronously.
    """

    async def inner(routing_key: str, subject: UUID) -> None:
        r = await test_client.post(
            f"/{routing_key}",
            json=jsonable_encoder(Event(subject=subject, priority=1)),
        )
        r.raise_for_status()

    return inner
