# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""IT-users are synced for engagements valid now (Nutid) or in the future
(Fremtid). Previously only engagements valid right now produced a position."""

import uuid
from collections.abc import Awaitable
from collections.abc import Callable
from datetime import datetime
from datetime import timedelta

import pytest
from httpx import AsyncClient
from more_itertools import one

from os2mo_rollekatalog.autogenerated_graphql_client import EmployeeCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_future_engagement_is_synced(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_engagement: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """A person whose only engagement starts in the future is synced with a
    position."""
    # Arrange: a unit, and a person whose only engagement starts in a year.
    await create_org_unit(name="Root", uuid=root_uuid)
    org_unit = await create_org_unit(name="OU", parent=root_uuid)
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Fætter", surname="Højben")
        )
    ).uuid
    # Engagement that only becomes valid in a year.
    future = datetime.now() + timedelta(days=365)
    eng = await create_engagement(org_unit=org_unit, person=employee, from_=future)

    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid = uuid.uuid4()
    external_id = uuid.uuid4()
    await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="FH",
        engagements=[eng],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
        engagements=[eng],
    )

    # Act.
    response = await test_client.post(f"/sync/person/{employee}")
    assert response.status_code == 200, response.text

    # Assert: the user is synced with a position in the future engagement's unit.
    assert (await test_client.get(f"/cache/person/{employee}")).json() == [
        {
            "extUuid": str(external_id),
            "nemloginUuid": None,
            "userId": "FH",
            "name": "Fætter Højben",
            "email": None,
            "positions": [{"name": "Jurist", "orgUnitUuid": str(org_unit)}],
            "functions": [],
        }
    ]


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_current_and_future_engagements_both_synced(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_engagement: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """A person with one current and one future engagement gets both positions."""
    # Arrange: two units, and a person with a current engagement in one and a
    # future engagement in the other.
    await create_org_unit(name="Root", uuid=root_uuid)
    unit_a = await create_org_unit(name="Unit A", parent=root_uuid)
    unit_b = await create_org_unit(name="Unit B", parent=root_uuid)
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Anders", surname="And")
        )
    ).uuid
    current_eng = await create_engagement(org_unit=unit_a, person=employee)
    future = datetime.now() + timedelta(days=365)
    future_eng = await create_engagement(org_unit=unit_b, person=employee, from_=future)

    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid = uuid.uuid4()
    external_id = uuid.uuid4()
    await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="AA",
        engagements=[current_eng, future_eng],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
        engagements=[current_eng, future_eng],
    )

    # Act.
    response = await test_client.post(f"/sync/person/{employee}")
    assert response.status_code == 200, response.text

    # Assert: both engagements produce a position.
    cached = (await test_client.get(f"/cache/person/{employee}")).json()
    positions = one(cached)["positions"]
    assert sorted(positions, key=lambda p: p["orgUnitUuid"]) == sorted(
        [
            {"name": "Jurist", "orgUnitUuid": str(unit_a)},
            {"name": "Jurist", "orgUnitUuid": str(unit_b)},
        ],
        key=lambda p: p["orgUnitUuid"],
    )
