# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Org units in EXCLUDE_ORG_UNITS (and their descendants) are not synced, and
never produce person positions."""

import uuid
from collections.abc import Awaitable
from collections.abc import Callable

import pytest
from httpx import AsyncClient

from os2mo_rollekatalog.autogenerated_graphql_client import EmployeeCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient

EXCLUDED = "00000000-0000-4000-0000-000000000001"


@pytest.mark.integration_test
@pytest.mark.envvar(
    {"LISTEN_TO_CHANGES_IN_MO": "False", "EXCLUDE_ORG_UNITS": f'["{EXCLUDED}"]'}
)
async def test_excluded_org_unit_and_descendants_are_not_synced(
    test_client: AsyncClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """The excluded unit and its descendants are not synced, while a sibling
    outside the excluded subtree still is."""
    # Arrange: root with an excluded unit + a child under it, and a kept sibling.
    await create_org_unit(name="Root", uuid=root_uuid)
    excluded = await create_org_unit(
        name="Excluded", parent=root_uuid, uuid=uuid.UUID(EXCLUDED)
    )
    excluded_child = await create_org_unit(name="Excluded child", parent=excluded)
    kept = await create_org_unit(name="Kept", parent=root_uuid)

    # Act: sync all three.
    for org_unit in (excluded, excluded_child, kept):
        await trigger_event("org_unit", org_unit)

    # Assert: the excluded subtree is absent from the cache; the sibling is present.
    assert (await test_client.get(f"/cache/org_unit/{excluded}")).json() is None
    assert (await test_client.get(f"/cache/org_unit/{excluded_child}")).json() is None
    assert (await test_client.get(f"/cache/org_unit/{kept}")).json() == {
        "uuid": str(kept),
        "name": "Kept",
        "parentOrgUnitUuid": str(root_uuid),
        "manager": None,
        "klePerforming": [],
        "kleInterest": [],
    }


@pytest.mark.integration_test
@pytest.mark.envvar(
    {"LISTEN_TO_CHANGES_IN_MO": "False", "EXCLUDE_ORG_UNITS": f'["{EXCLUDED}"]'}
)
async def test_person_keeps_only_positions_in_kept_units(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_engagement: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """A person with engagements in both an excluded and a kept unit is synced
    with only the position in the kept unit."""
    # Arrange: an excluded unit and a kept unit.
    await create_org_unit(name="Root", uuid=root_uuid)
    excluded = await create_org_unit(
        name="Excluded", parent=root_uuid, uuid=uuid.UUID(EXCLUDED)
    )
    kept = await create_org_unit(name="Kept", parent=root_uuid)
    # ... and a person with an engagement in each.
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Anders", surname="And")
        )
    ).uuid
    eng_excluded = await create_engagement(org_unit=excluded, person=employee)
    eng_kept = await create_engagement(org_unit=kept, person=employee)
    # A matching AD + FK-org ituser pair (linked by external_id) makes the person
    # a syncable Rollekatalog user.
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid = uuid.uuid4()
    external_id = uuid.uuid4()
    await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="AA",
        engagements=[eng_excluded, eng_kept],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
        engagements=[eng_excluded, eng_kept],
    )

    # Act.
    await trigger_event("person", employee)

    # Assert: only the kept unit's position survives.
    assert (await test_client.get(f"/cache/person/{employee}")).json() == [
        {
            "extUuid": str(external_id),
            "nemloginUuid": None,
            "userId": "AA",
            "name": "Anders And",
            "email": None,
            "positions": [{"name": "Jurist", "orgUnitUuid": str(kept)}],
            "functions": [],
        }
    ]


@pytest.mark.integration_test
@pytest.mark.envvar(
    {"LISTEN_TO_CHANGES_IN_MO": "False", "EXCLUDE_ORG_UNITS": f'["{EXCLUDED}"]'}
)
async def test_person_with_only_excluded_engagements_is_not_synced(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_engagement: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """A person whose only engagement is in an excluded unit is not synced.

    Contrast with test_user_without_engagements_is_kept: having engagements that
    all resolve to excluded units drops the user, but having no engagements at
    all does not (#70811)."""
    # Arrange: only an excluded unit, and a person with an engagement there.
    await create_org_unit(name="Root", uuid=root_uuid)
    excluded = await create_org_unit(
        name="Excluded", parent=root_uuid, uuid=uuid.UUID(EXCLUDED)
    )
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Fedt", surname="mule")
        )
    ).uuid
    eng = await create_engagement(org_unit=excluded, person=employee)
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid = uuid.uuid4()
    external_id = uuid.uuid4()
    await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="FM",
        engagements=[eng],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
        engagements=[eng],
    )

    # Act.
    await trigger_event("person", employee)

    # Assert: the person is not in the cache.
    assert (await test_client.get(f"/cache/person/{employee}")).json() == []


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_user_without_engagements_is_kept(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """A user with no engagements at all is still synced (with no positions).

    The exclusion drop-rule only drops users whose engagements *all* resolve to
    excluded units; a user that simply has no engagements must not be dropped
    (#70811)."""
    # Arrange: a person with an AD + FK-org ituser pair but no engagements.
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Joakim", surname="von And")
        )
    ).uuid
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid = uuid.uuid4()
    external_id = uuid.uuid4()
    await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="JvA",
        engagements=[],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
        engagements=[],
    )

    # Act.
    await trigger_event("person", employee)

    # Assert: the user is synced with an empty positions list.
    assert (await test_client.get(f"/cache/person/{employee}")).json() == [
        {
            "extUuid": str(external_id),
            "nemloginUuid": None,
            "userId": "JvA",
            "name": "Joakim von And",
            "email": None,
            "positions": [],
            "functions": [],
        }
    ]
