# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""A person with itusers in two AD-like itsystems syncs both.

Some customers run more than one AD-like itsystem (e.g. a regular AD
plus a separate "Skole-AD"), configured via AD_ITSYSTEM_USER_KEYS. Each
AD ituser is mapped to FK-org the same way (its external_id matched
against an FK ituser's user_key), so the person should get one
Rollekatalog user per AD account.
"""

import uuid

import pytest
from httpx import AsyncClient

from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_multiple_ad_itsystems_map_to_fk(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
) -> None:
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    await graphql_client._testing__create_org_unit_root(
        root_uuid=root_uuid, name="Root", org_unit_type=org_unit_type
    )
    org_unit = (
        await graphql_client._testing__create_org_unit(
            name="OU", parent=root_uuid, org_unit_type=org_unit_type
        )
    ).uuid
    employee = (
        await graphql_client._testing__create_employee(
            first_name="Multi", last_name="AD"
        )
    ).uuid
    engagement_type = (
        (await graphql_client._testing__get_engagement_type())
        .objects[0]
        .current.classes[0]  # type: ignore
        .uuid
    )
    job_function = (
        (await graphql_client._testing__get_job_function())
        .objects[0]
        .current.classes[0]  # type: ignore
    )
    eng = (
        await graphql_client._testing__create_engagement(
            org_unit, employee, engagement_type, job_function.uuid
        )
    ).uuid

    # Two AD-like itsystems, both mapped to the same FK-org itsystem.
    AD = (await graphql_client._testing__create_it_system("Active Directory")).uuid
    SKOLE_AD = (await graphql_client._testing__create_it_system("Skole-AD")).uuid
    FK = (await graphql_client._testing__create_it_system("FK ORG")).uuid

    # Regular AD account + its FK pairing.
    ad_object_guid = uuid.uuid4()
    ad_external_id = uuid.uuid4()
    await graphql_client._testing__create_it_user(
        AD, str(ad_object_guid), employee, "AA", None, [eng]
    )
    await graphql_client._testing__create_it_user(
        FK, str(ad_external_id), employee, str(ad_object_guid), None, [eng]
    )

    # Skole-AD account + its FK pairing.
    skole_object_guid = uuid.uuid4()
    skole_external_id = uuid.uuid4()
    await graphql_client._testing__create_it_user(
        SKOLE_AD, str(skole_object_guid), employee, "AA-skole", None, [eng]
    )
    await graphql_client._testing__create_it_user(
        FK, str(skole_external_id), employee, str(skole_object_guid), None, [eng]
    )

    response = await test_client.post(f"/sync/person/{employee}")
    assert response.status_code == 200, response.text

    cached = (await test_client.get(f"/cache/person/{employee}")).json()
    cached = sorted(cached, key=lambda u: u["userId"])
    assert cached == [
        {
            "extUuid": str(ad_external_id),
            "nemloginUuid": None,
            "userId": "AA",
            "name": "Multi AD",
            "email": None,
            "positions": [
                {"name": job_function.name, "orgUnitUuid": str(org_unit)},
            ],
        },
        {
            "extUuid": str(skole_external_id),
            "nemloginUuid": None,
            "userId": "AA-skole",
            "name": "Multi AD",
            "email": None,
            "positions": [
                {"name": job_function.name, "orgUnitUuid": str(org_unit)},
            ],
        },
    ]
