# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Org units are synced through the real event listeners.

These tests leave LISTEN_TO_CHANGES_IN_MO on, so they cover the whole
event-driven path: MO change → GraphQL event → listener → cache. Assertions
retry while the events propagate.
"""

import uuid
from collections.abc import Awaitable
from collections.abc import Callable
from datetime import datetime

import pytest
from fastramqpi.pytest_util import retry
from httpx import AsyncClient

from os2mo_rollekatalog.autogenerated_graphql_client import ClassCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import EmployeeCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient
from os2mo_rollekatalog.autogenerated_graphql_client import OrganisationUnitUpdateInput
from os2mo_rollekatalog.autogenerated_graphql_client import RAValidityInput
from tests.integration.conftest import SEED_RA_VALIDITY
from tests.integration.conftest import SEED_VALIDITY


def _unit(unit: uuid.UUID, name: str, parent: uuid.UUID | None) -> dict[str, object]:
    """The cache payload of a plain org unit."""
    return {
        "uuid": str(unit),
        "name": name,
        "parentOrgUnitUuid": str(parent) if parent else None,
        "manager": None,
        "klePerforming": [],
        "kleInterest": [],
    }


@pytest.mark.integration_test
async def test_hierarchy_is_synced(
    test_client: AsyncClient,
    root_uuid: uuid.UUID,
    external_roots: list[uuid.UUID],
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """Units below ROOT_ORG_UNIT are synced with their parent links, and an
    external root is placed under ROOT_ORG_UNIT."""
    await create_org_unit(name="Root", uuid=root_uuid)
    layer1 = await create_org_unit(name="Layer 1", parent=root_uuid)
    layer2 = await create_org_unit(name="Layer 2", parent=layer1)
    external_root = await create_org_unit(name="External root", uuid=external_roots[0])
    external_unit = await create_org_unit(name="External unit", parent=external_root)

    @retry()
    async def validate_hierarchy() -> None:
        get = test_client.get
        assert (await get(f"/cache/org_unit/{root_uuid}")).json() == _unit(
            root_uuid, "Root", None
        )
        assert (await get(f"/cache/org_unit/{layer1}")).json() == _unit(
            layer1, "Layer 1", root_uuid
        )
        assert (await get(f"/cache/org_unit/{layer2}")).json() == _unit(
            layer2, "Layer 2", layer1
        )
        # External roots hang directly under the root org unit.
        assert (await get(f"/cache/org_unit/{external_root}")).json() == _unit(
            external_root, "External root", root_uuid
        )
        assert (await get(f"/cache/org_unit/{external_unit}")).json() == _unit(
            external_unit, "External unit", external_root
        )

    await validate_hierarchy()


@pytest.mark.integration_test
async def test_rename_is_synced(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """Renaming a unit in MO renames it in the cache."""
    await create_org_unit(name="Root", uuid=root_uuid)
    unit = await create_org_unit(name="Old Name", parent=root_uuid)

    @retry()
    async def observe_unit() -> None:
        assert (await test_client.get(f"/cache/org_unit/{unit}")).json() == _unit(
            unit, "Old Name", root_uuid
        )

    await observe_unit()

    await graphql_client._testing__update_org_unit(
        input=OrganisationUnitUpdateInput(
            uuid=unit, name="New Name", validity=SEED_RA_VALIDITY
        )
    )

    @retry()
    async def observe_name_change() -> None:
        assert (await test_client.get(f"/cache/org_unit/{unit}")).json() == _unit(
            unit, "New Name", root_uuid
        )

    await observe_name_change()


@pytest.mark.integration_test
async def test_excluded_level_subtree_is_not_synced(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
    exclude_org_unit_level: uuid.UUID,
    org_unit_level_facet: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """A unit on EXCLUDE_ORG_UNIT_LEVEL is not synced, nor are its
    descendants, while a sibling on no particular level still is."""
    level = (
        await graphql_client._testing__create_class(
            input=ClassCreateInput(
                user_key="Udgået",
                name="Udgået",
                facet_uuid=org_unit_level_facet,
                uuid=exclude_org_unit_level,
                validity=SEED_VALIDITY,
            )
        )
    ).uuid
    await create_org_unit(name="Root", uuid=root_uuid)
    excluded = await create_org_unit(
        name="Excluded", parent=root_uuid, org_unit_level=level
    )
    excluded_child = await create_org_unit(name="Excluded child", parent=excluded)
    kept = await create_org_unit(name="Kept", parent=root_uuid)

    @retry()
    async def validate() -> None:
        assert (await test_client.get(f"/cache/org_unit/{kept}")).json() == _unit(
            kept, "Kept", root_uuid
        )
        assert (await test_client.get(f"/cache/org_unit/{excluded}")).json() is None
        assert (
            await test_client.get(f"/cache/org_unit/{excluded_child}")
        ).json() is None

    await validate()


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_unit_moved_out_of_tree_is_removed(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_engagement: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """Moving a unit out of the synced tree removes it, its descendants, and
    the users whose positions all pointed into the removed subtree.

    Driven through trigger_event: with a listener on, a person re-sync could
    race the removal and re-add the user without positions (#70811), so the
    cascade is asserted deterministically instead.
    """
    await create_org_unit(name="Root", uuid=root_uuid)
    moved = await create_org_unit(name="Moved", parent=root_uuid)
    child = await create_org_unit(name="Child", parent=moved)
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Anders", surname="And")
        )
    ).uuid
    eng = await create_engagement(org_unit=child, person=employee)
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid, external_id = uuid.uuid4(), uuid.uuid4()
    await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="AA",
        engagements=[eng],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
        engagements=[eng],
    )
    for org_unit in (moved, child):
        await trigger_event("org_unit", org_unit)
    await trigger_event("person", employee)
    assert (await test_client.get(f"/cache/org_unit/{child}")).json() is not None
    assert (await test_client.get(f"/cache/person/{employee}")).json() != []

    # Make the unit a root of its own, outside ROOT_ORG_UNIT's tree.
    await graphql_client._testing__update_org_unit(
        input=OrganisationUnitUpdateInput(
            uuid=moved, parent=None, validity=RAValidityInput(from_=datetime.now())
        )
    )
    await trigger_event("org_unit", moved)

    assert (await test_client.get(f"/cache/org_unit/{moved}")).json() is None
    assert (await test_client.get(f"/cache/org_unit/{child}")).json() is None
    assert (await test_client.get(f"/cache/person/{employee}")).json() == []
