# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""A person with itusers in two AD-like itsystems syncs both.

Some customers run more than one AD-like itsystem (e.g. a regular AD
plus a separate "Skole-AD"), configured via AD_ITSYSTEM_USER_KEYS. Each
AD ituser is mapped to FK-org the same way (its external_id matched
against an FK ituser's user_key), so the person should get one
Rollekatalog user per AD account.
"""

import uuid
from collections.abc import Awaitable
from collections.abc import Callable

import pytest
from httpx import AsyncClient

from os2mo_rollekatalog.autogenerated_graphql_client import EmployeeCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_multiple_ad_itsystems_map_to_fk(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_engagement: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    await create_org_unit(name="Root", uuid=root_uuid)
    org_unit = await create_org_unit(name="OU", parent=root_uuid)
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Multi", surname="AD")
        )
    ).uuid
    eng = await create_engagement(org_unit=org_unit, person=employee)

    # Two AD-like itsystems, both mapped to the same FK-org itsystem.
    AD = await create_it_system("Active Directory")
    SKOLE_AD = await create_it_system("Skole-AD")
    FK = await create_it_system("FK ORG")

    # Regular AD account + its FK pairing.
    ad_object_guid = uuid.uuid4()
    ad_external_id = uuid.uuid4()
    await create_ituser(
        itsystem=AD,
        external_id=str(ad_object_guid),
        person=employee,
        user_key="AA",
        engagements=[eng],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(ad_external_id),
        person=employee,
        user_key=str(ad_object_guid),
        engagements=[eng],
    )

    # Skole-AD account + its FK pairing.
    skole_object_guid = uuid.uuid4()
    skole_external_id = uuid.uuid4()
    await create_ituser(
        itsystem=SKOLE_AD,
        external_id=str(skole_object_guid),
        person=employee,
        user_key="AA-skole",
        engagements=[eng],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(skole_external_id),
        person=employee,
        user_key=str(skole_object_guid),
        engagements=[eng],
    )

    response = await test_client.post(f"/sync/person/{employee}")
    assert response.status_code == 200, response.text

    cached = (await test_client.get(f"/cache/person/{employee}")).json()
    cached = sorted(cached, key=lambda u: u["userId"])
    assert cached == [
        {
            "extUuid": str(ad_external_id),
            "nemloginUuid": None,
            "userId": "AA",
            "name": "Multi AD",
            "email": None,
            "positions": [
                {"name": "Jurist", "orgUnitUuid": str(org_unit)},
            ],
            "functions": [],
        },
        {
            "extUuid": str(skole_external_id),
            "nemloginUuid": None,
            "userId": "AA-skole",
            "name": "Multi AD",
            "email": None,
            "positions": [
                {"name": "Jurist", "orgUnitUuid": str(org_unit)},
            ],
            "functions": [],
        },
    ]
