# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Which manager an org unit reports."""

import uuid
from collections.abc import Awaitable
from collections.abc import Callable

import pytest
from httpx import AsyncClient

from os2mo_rollekatalog.autogenerated_graphql_client import EmployeeCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_manager_without_engagement_is_synced(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_manager: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """A manager is synced whether or not they have an engagement."""
    # Arrange: a unit and a manager with no engagement at all.
    await create_org_unit(name="Root", uuid=root_uuid)
    managed = await create_org_unit(name="Managed", parent=root_uuid)
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Anders", surname="And")
        )
    ).uuid
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid = uuid.uuid4()
    external_id = uuid.uuid4()
    await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="AA",
        engagements=[],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
        engagements=[],
    )
    await create_manager(person=employee, org_unit=managed)

    # Act.
    await trigger_event("org_unit", managed)

    # Assert.
    manager = (await test_client.get(f"/cache/org_unit/{managed}")).json()["manager"]
    assert manager["userId"] == "AA"
    assert manager["uuid"] == str(external_id)


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "MANAGER_ITSYSTEM_USER_KEY": "Active Directory",
    }
)
async def test_manager_account_is_from_manager_itsystem(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_manager: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """Only accounts in MANAGER_ITSYSTEM_USER_KEY carry manager rights.

    The ituser UUIDs are pinned so the Skole-AD account would win if the
    itsystem were ignored."""
    # Arrange: a manager with an account in each AD itsystem.
    await create_org_unit(name="Root", uuid=root_uuid)
    managed = await create_org_unit(name="Managed", parent=root_uuid)
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Anders", surname="And")
        )
    ).uuid
    AD = await create_it_system("Active Directory")
    SKOLE = await create_it_system("Skole-AD")
    FK = await create_it_system("FK ORG")
    skole_guid, skole_external = uuid.uuid4(), uuid.uuid4()
    ad_guid, ad_external = uuid.uuid4(), uuid.uuid4()
    await create_ituser(
        itsystem=SKOLE,
        external_id=str(skole_guid),
        person=employee,
        user_key="SKOLE",
        uuid=uuid.UUID("00000000-0000-4000-0000-000000000001"),
        engagements=[],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(skole_external),
        person=employee,
        user_key=str(skole_guid),
        engagements=[],
    )
    await create_ituser(
        itsystem=AD,
        external_id=str(ad_guid),
        person=employee,
        user_key="AD",
        uuid=uuid.UUID("ffffffff-0000-4000-0000-000000000002"),
        engagements=[],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(ad_external),
        person=employee,
        user_key=str(ad_guid),
        engagements=[],
    )
    await create_manager(person=employee, org_unit=managed)

    # Act.
    await trigger_event("org_unit", managed)

    # Assert: the Active Directory account carries the manager rights.
    manager = (await test_client.get(f"/cache/org_unit/{managed}")).json()["manager"]
    assert manager["userId"] == "AD"
    assert manager["uuid"] == str(ad_external)


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "MANAGER_ITSYSTEM_USER_KEY": "Active Directory",
    }
)
async def test_manager_with_only_other_itsystem_account_is_not_synced(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_manager: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """A manager with no account in MANAGER_ITSYSTEM_USER_KEY is not reported."""
    # Arrange: a manager with a resolvable Skole-AD account and nothing else.
    await create_org_unit(name="Root", uuid=root_uuid)
    managed = await create_org_unit(name="Managed", parent=root_uuid)
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Joakim", surname="von And")
        )
    ).uuid
    SKOLE = await create_it_system("Skole-AD")
    FK = await create_it_system("FK ORG")
    object_guid, external_id = uuid.uuid4(), uuid.uuid4()
    await create_ituser(
        itsystem=SKOLE,
        external_id=str(object_guid),
        person=employee,
        user_key="SKOLE",
        engagements=[],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
        engagements=[],
    )
    await create_manager(person=employee, org_unit=managed)

    # Act.
    await trigger_event("org_unit", managed)

    # Assert.
    org_unit = (await test_client.get(f"/cache/org_unit/{managed}")).json()
    assert org_unit["manager"] is None


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_manager_without_fk_org_account_is_not_synced(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_manager: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """A manager without an FK-org account has no extUuid, so is left out."""
    # Arrange: a manager whose FK-org account carries no external_id.
    await create_org_unit(name="Root", uuid=root_uuid)
    managed = await create_org_unit(name="Managed", parent=root_uuid)
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Joakim", surname="von And")
        )
    ).uuid
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid = uuid.uuid4()
    await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="JvA",
        engagements=[],
    )
    await create_ituser(
        itsystem=FK,
        external_id="",
        person=employee,
        user_key=str(object_guid),
        engagements=[],
    )
    await create_manager(person=employee, org_unit=managed)

    # Act.
    await trigger_event("org_unit", managed)

    # Assert.
    org_unit = (await test_client.get(f"/cache/org_unit/{managed}")).json()
    assert org_unit["manager"] is None
