# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Reproduce duplicate-key spam from concurrent sync_person calls.

When a person is created in MO, several events fan out (person, ituser,
address, engagement) and each one calls sync_person on the same person
in its own transaction. They all observe an empty DB, all queue an
INSERT for the same row, and only the first commit wins — the others
fail with a duplicate-key violation on the unique extUuid.
"""

import asyncio
import uuid
from unittest.mock import patch

import pytest
from fastramqpi.pytest_util import retry
from httpx import AsyncClient

from os2mo_rollekatalog import person as person_module
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient


CONCURRENT = 10


@pytest.mark.integration_test
@pytest.mark.no_amqp
async def test_concurrent_sync_person_no_duplicate_key_error(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
    caplog: pytest.LogCaptureFixture,
) -> None:
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    await graphql_client._testing__create_org_unit_root(
        root_uuid=root_uuid,
        name="Root",
        org_unit_type=org_unit_type,
    )
    org_unit = (
        await graphql_client._testing__create_org_unit(
            name="OU",
            parent=root_uuid,
            org_unit_type=org_unit_type,
        )
    ).uuid

    employee = (
        await graphql_client._testing__create_employee(
            first_name="Concurrent",
            last_name="User",
        )
    ).uuid

    engagement_type = (
        (await graphql_client._testing__get_engagement_type())
        .objects[0]
        .current.classes[0]  # type: ignore
        .uuid
    )
    job_function = (
        (await graphql_client._testing__get_job_function())
        .objects[0]
        .current.classes[0]  # type: ignore
    )
    eng = (
        await graphql_client._testing__create_engagement(
            org_unit, employee, engagement_type, job_function.uuid
        )
    ).uuid

    AD = (await graphql_client._testing__create_it_system("Active Directory")).uuid
    FK = (await graphql_client._testing__create_it_system("FK ORG")).uuid
    object_guid = uuid.uuid4()
    external_id = uuid.uuid4()
    await graphql_client._testing__create_it_user(
        AD, str(object_guid), employee, "CU", None, [eng]
    )
    await graphql_client._testing__create_it_user(
        FK, str(external_id), employee, str(object_guid), None, [eng]
    )

    # AMQP is disabled for this test, so the cache stays empty until our
    # POSTs run. We only need to wait for MO to be consistent enough that
    # /debug/person resolves the user.
    @retry()
    async def wait_for_mo() -> None:
        debug = (await test_client.get(f"/debug/person/{employee}")).json()
        assert isinstance(debug, list) and debug, f"MO not ready: {debug}"

    await wait_for_mo()

    # Gate every concurrent sync_person between its SELECT and its
    # INSERT/COMMIT, so all N transactions are guaranteed to have
    # observed an empty DB before any of them attempts to write.
    # Without this, asyncio.gather doesn't reliably reproduce the race
    # because one task can finish its commit before the next reads.
    #
    # The wait has a timeout so that when the production code is
    # properly serialized (by the advisory lock), the lone task at the
    # barrier proceeds after 1s, and subsequent tasks get
    # BrokenBarrierError and proceed too — no deadlock.
    barrier = asyncio.Barrier(CONCURRENT)
    real_fetch = person_module.fetch_users_from_db

    async def synchronized_fetch(session, p_uuid):
        result = await real_fetch(session, p_uuid)
        if p_uuid == employee:
            try:
                await asyncio.wait_for(barrier.wait(), timeout=1.0)
            except (asyncio.TimeoutError, asyncio.BrokenBarrierError):
                pass
        return result

    caplog.clear()
    with patch(
        "os2mo_rollekatalog.person.fetch_users_from_db",
        new=synchronized_fetch,
    ), caplog.at_level("INFO", logger="os2mo_rollekatalog.person"):
        responses = await asyncio.gather(
            *(test_client.post(f"/sync/person/{employee}") for _ in range(CONCURRENT)),
            return_exceptions=True,
        )

    for r in responses:
        assert not isinstance(r, BaseException), f"request raised: {r!r}"
        assert r.status_code == 200, f"request failed: {r.status_code} {r.text}"

    add_count = sum(1 for r in caplog.records if "Add new user" in r.getMessage())
    unchanged_count = sum(
        1 for r in caplog.records if "User unchanged" in r.getMessage()
    )
    assert add_count == 1, f"expected exactly one Add new user, got {add_count}"
    assert (
        unchanged_count == CONCURRENT - 1
    ), f"expected {CONCURRENT - 1} User unchanged, got {unchanged_count}"

    cached = (await test_client.get(f"/cache/person/{employee}")).json()
    assert cached == [
        {
            "extUuid": str(external_id),
            "nemloginUuid": None,
            "userId": "CU",
            "name": "Concurrent User",
            "email": None,
            "positions": [
                {
                    "name": job_function.name,
                    "orgUnitUuid": str(org_unit),
                }
            ],
        }
    ]
