# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Which email a synced user gets."""

import uuid
from datetime import datetime
from datetime import timedelta

import pytest
from httpx import AsyncClient
from more_itertools import one

from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_email_linked_to_ituser_goes_to_that_account(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event,
    root_uuid: uuid.UUID,
    email_address_type: uuid.UUID,
) -> None:
    """An email linked to an ituser is only used for that account."""
    # Arrange: a person with two AD accounts, and an email linked to one.
    employee = (
        await graphql_client._testing__create_employee(
            first_name="Anders", last_name="And"
        )
    ).uuid
    AD = (await graphql_client._testing__create_it_system("Active Directory")).uuid
    FK = (await graphql_client._testing__create_it_system("FK ORG")).uuid
    linked_guid, linked_external = uuid.uuid4(), uuid.uuid4()
    other_guid, other_external = uuid.uuid4(), uuid.uuid4()
    linked_ituser = (
        await graphql_client._testing__create_it_user(
            AD, str(linked_guid), employee, "LINKED", None, []
        )
    ).uuid
    await graphql_client._testing__create_it_user(
        FK, str(linked_external), employee, str(linked_guid), None, []
    )
    await graphql_client._testing__create_it_user(
        AD, str(other_guid), employee, "OTHER", None, []
    )
    await graphql_client._testing__create_it_user(
        FK, str(other_external), employee, str(other_guid), None, []
    )
    await graphql_client._testing__create_address(
        employee,
        "linked@example.org",
        email_address_type,
        ituser=linked_ituser,
    )

    # Act.
    await trigger_event("person", employee)

    # Assert: only the linked account gets the email.
    users = (await test_client.get(f"/cache/person/{employee}")).json()
    email_by_user = {user["userId"]: user["email"] for user in users}
    assert email_by_user == {"LINKED": "linked@example.org", "OTHER": None}


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_unlinked_email_is_used_for_any_account(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event,
    root_uuid: uuid.UUID,
    email_address_type: uuid.UUID,
) -> None:
    """An email with no ituser link is used as a fallback (linking an
    address to an ituser is optional in MO)."""
    # Arrange: a person with one AD account and an unlinked email.
    employee = (
        await graphql_client._testing__create_employee(
            first_name="Joakim", last_name="von And"
        )
    ).uuid
    AD = (await graphql_client._testing__create_it_system("Active Directory")).uuid
    FK = (await graphql_client._testing__create_it_system("FK ORG")).uuid
    object_guid, external_id = uuid.uuid4(), uuid.uuid4()
    await graphql_client._testing__create_it_user(
        AD, str(object_guid), employee, "JvA", None, []
    )
    await graphql_client._testing__create_it_user(
        FK, str(external_id), employee, str(object_guid), None, []
    )
    await graphql_client._testing__create_address(
        employee, "unlinked@example.org", email_address_type
    )

    # Act.
    await trigger_event("person", employee)

    # Assert.
    user = one((await test_client.get(f"/cache/person/{employee}")).json())
    assert user["email"] == "unlinked@example.org"


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_current_email_preferred_over_future(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event,
    root_uuid: uuid.UUID,
    email_address_type: uuid.UUID,
) -> None:
    """With one address valid now and one only valid in the future, the
    current one is used."""
    # Arrange: a person with one AD account and two linked emails, one of
    # which only becomes valid in a year.
    employee = (
        await graphql_client._testing__create_employee(
            first_name="Andersine", last_name="And"
        )
    ).uuid
    AD = (await graphql_client._testing__create_it_system("Active Directory")).uuid
    FK = (await graphql_client._testing__create_it_system("FK ORG")).uuid
    object_guid, external_id = uuid.uuid4(), uuid.uuid4()
    ituser = (
        await graphql_client._testing__create_it_user(
            AD, str(object_guid), employee, "AsA", None, []
        )
    ).uuid
    await graphql_client._testing__create_it_user(
        FK, str(external_id), employee, str(object_guid), None, []
    )
    await graphql_client._testing__create_address(
        employee,
        "future@example.org",
        email_address_type,
        ituser=ituser,
        from_=datetime.now() + timedelta(days=365),
    )
    await graphql_client._testing__create_address(
        employee, "current@example.org", email_address_type, ituser=ituser
    )

    # Act.
    await trigger_event("person", employee)

    # Assert.
    user = one((await test_client.get(f"/cache/person/{employee}")).json())
    assert user["email"] == "current@example.org"


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_newest_email_wins_among_multiple_current(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event,
    root_uuid: uuid.UUID,
    email_address_type: uuid.UUID,
) -> None:
    """With several currently valid addresses, the newest one is used — the
    one whose validity starts latest — not the most recently edited."""
    # Arrange: two linked emails, both valid now. The 2014 one is edited
    # recently (its current version then starts after the 2020 one). Newest
    # created first so query order cannot accidentally satisfy the assert.
    employee = (
        await graphql_client._testing__create_employee(
            first_name="Georg", last_name="Gearløs"
        )
    ).uuid
    AD = (await graphql_client._testing__create_it_system("Active Directory")).uuid
    FK = (await graphql_client._testing__create_it_system("FK ORG")).uuid
    object_guid, external_id = uuid.uuid4(), uuid.uuid4()
    ituser = (
        await graphql_client._testing__create_it_user(
            AD, str(object_guid), employee, "GG", None, []
        )
    ).uuid
    await graphql_client._testing__create_it_user(
        FK, str(external_id), employee, str(object_guid), None, []
    )
    await graphql_client._testing__create_address(
        employee,
        "newest@example.org",
        email_address_type,
        ituser=ituser,
        from_=datetime(2020, 1, 1),
    )
    oldest = (
        await graphql_client._testing__create_address(
            employee, "oldest@example.org", email_address_type, ituser=ituser
        )
    ).uuid
    await graphql_client._testing__update_address(
        oldest,
        employee,
        "oldest-edited@example.org",
        email_address_type,
        ituser=ituser,
        from_=datetime(2026, 1, 1),
    )

    # Act.
    await trigger_event("person", employee)

    # Assert.
    user = one((await test_client.get(f"/cache/person/{employee}")).json())
    assert user["email"] == "newest@example.org"
