# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Tillidsfunktioner: each person's associations, synced as functions."""

import uuid
from collections.abc import Awaitable
from collections.abc import Callable

import pytest
from httpx import AsyncClient
from more_itertools import one

from os2mo_rollekatalog.autogenerated_graphql_client import EmployeeCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False", "SYNC_FUNCTIONS": "true"})
async def test_functions_endpoint_exposes_association_types(
    test_client: AsyncClient,
    tillidsrepraesentant: uuid.UUID,
) -> None:
    """The function catalog is the association types, with MO's UUIDs."""
    functions = (await test_client.get("/functions")).json()
    assert functions == [
        {"uuid": str(tillidsrepraesentant), "name": "Tillidsrepræsentant"}
    ]


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False", "SYNC_FUNCTIONS": "true"})
async def test_person_association_becomes_function(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    tillidsrepraesentant: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_association: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """A person's association is synced as a function referencing the
    association type by UUID, which is also the function's UUID in
    Rollekatalog."""
    await create_org_unit(name="Root", uuid=root_uuid)
    unit = await create_org_unit(name="Unit", parent=root_uuid)
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Georg", surname="Gearløs")
        )
    ).uuid
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid, external_id = uuid.uuid4(), uuid.uuid4()
    await create_ituser(
        itsystem=AD, external_id=str(object_guid), person=employee, user_key="GG"
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
    )
    await create_association(org_unit=unit, person=employee)

    await trigger_event("person", employee)

    user = one((await test_client.get(f"/cache/person/{employee}")).json())
    assert user["functions"] == [
        {"ouUuid": str(unit), "functionUuid": str(tillidsrepraesentant)}
    ]


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False", "SYNC_FUNCTIONS": "true"})
async def test_association_event_syncs_person(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    tillidsrepraesentant: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_association: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """An association event resolves to the person and syncs them."""
    await create_org_unit(name="Root", uuid=root_uuid)
    unit = await create_org_unit(name="Unit", parent=root_uuid)
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Georg", surname="Gearløs")
        )
    ).uuid
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid, external_id = uuid.uuid4(), uuid.uuid4()
    await create_ituser(
        itsystem=AD, external_id=str(object_guid), person=employee, user_key="GG"
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
    )
    association = await create_association(org_unit=unit, person=employee)

    await trigger_event("association", association)

    user = one((await test_client.get(f"/cache/person/{employee}")).json())
    assert user["functions"] == [
        {"ouUuid": str(unit), "functionUuid": str(tillidsrepraesentant)}
    ]


EXCLUDED = "00000000-0000-4000-0000-000000000001"


@pytest.mark.integration_test
@pytest.mark.envvar(
    {
        "LISTEN_TO_CHANGES_IN_MO": "False",
        "SYNC_FUNCTIONS": "true",
        "EXCLUDE_ORG_UNITS": f'["{EXCLUDED}"]',
    }
)
async def test_association_in_unsynced_org_unit_produces_no_function(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    tillidsrepraesentant: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_association: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """Associations in org units outside the sync tree or in an excluded unit
    never produce a function, so we never reference an org unit we don't
    sync."""
    await create_org_unit(name="Root", uuid=root_uuid)
    outside = await create_org_unit(name="Outside the sync tree")
    excluded = await create_org_unit(
        name="Excluded", parent=root_uuid, uuid=uuid.UUID(EXCLUDED)
    )
    kept = await create_org_unit(name="Kept", parent=root_uuid)
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Georg", surname="Gearløs")
        )
    ).uuid
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid, external_id = uuid.uuid4(), uuid.uuid4()
    await create_ituser(
        itsystem=AD, external_id=str(object_guid), person=employee, user_key="GG"
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
    )
    await create_association(org_unit=outside, person=employee)
    await create_association(org_unit=excluded, person=employee)
    await create_association(org_unit=kept, person=employee)

    await trigger_event("person", employee)

    user = one((await test_client.get(f"/cache/person/{employee}")).json())
    assert [f["ouUuid"] for f in user["functions"]] == [str(kept)]
