# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Reproduce duplicate-key spam on the unique user keys.

extUuid and nemloginUuid are unique across the whole table, while
sync_person only reconciles within one person, so a key we are about to
write can already be taken. Two families of cause:

Concurrency — when a person is created in MO, several events fan out
(person, ituser, address, engagement) and each one calls sync_person on
the same person in its own transaction. They all observe an empty DB,
all queue an INSERT for the same row, and only the first commit wins —
the others fail with a duplicate-key violation.

Foreign owners — the row holding the key belongs to a *different*
person: the account was handed over to another employee, or its owner
does not exist in MO at all (a manually created employee recreated with
a fresh UUID after a database copy between environments). Since the
reconciliation never looks at other persons' rows, these do not resolve
themselves; every redelivery of the event fails identically forever.
"""

import asyncio
import uuid
from dataclasses import dataclass
from datetime import datetime
from unittest.mock import patch

import pytest
from fastramqpi.pytest_util import retry
from httpx import AsyncClient
from sqlalchemy import text
from sqlalchemy.ext.asyncio import async_sessionmaker

from os2mo_rollekatalog import person as person_module
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient


CONCURRENT = 10


@dataclass
class Account:
    """An employee with a matched AD/FK ORG account pair."""

    employee: uuid.UUID
    ad_ituser: uuid.UUID
    fk_ituser: uuid.UUID
    object_guid: uuid.UUID
    fk_external_id: uuid.UUID
    user_key: str
    name: str


async def create_root_with_org_unit(
    graphql_client: GraphQLClient, root_uuid: uuid.UUID
) -> uuid.UUID:
    """Create the sync root with a single child org unit, and return the child."""
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    await graphql_client._testing__create_org_unit_root(
        root_uuid=root_uuid, name="Root", org_unit_type=org_unit_type
    )
    return (
        await graphql_client._testing__create_org_unit(
            name="OU", parent=root_uuid, org_unit_type=org_unit_type
        )
    ).uuid


async def create_employee_with_account(
    graphql_client: GraphQLClient,
    org_unit: uuid.UUID,
    engagement_type: uuid.UUID,
    job_function: uuid.UUID,
    first_name: str,
    last_name: str,
    user_key: str,
    mit_id: uuid.UUID | None = None,
) -> Account:
    """Create an employee with an engagement and a matched AD/FK account pair.

    The FK ORG ituser's user_key is the AD ituser's external_id (its
    objectGUID), which is how ``resolve_samaccounts`` pairs them, so the
    resulting extUuid is the FK ituser's external_id.
    """
    employee = (
        await graphql_client._testing__create_employee(
            first_name=first_name, last_name=last_name
        )
    ).uuid
    eng = (
        await graphql_client._testing__create_engagement(
            org_unit, employee, engagement_type, job_function
        )
    ).uuid

    AD = (await graphql_client._testing__create_it_system("Active Directory")).uuid
    FK = (await graphql_client._testing__create_it_system("FK ORG")).uuid
    object_guid = uuid.uuid4()
    fk_external_id = uuid.uuid4()
    ad_ituser = (
        await graphql_client._testing__create_it_user(
            AD, str(object_guid), employee, user_key, None, [eng]
        )
    ).uuid
    fk_ituser = (
        await graphql_client._testing__create_it_user(
            FK, str(fk_external_id), employee, str(object_guid), None, [eng]
        )
    ).uuid

    if mit_id is not None:
        mit_id_class = (
            (await graphql_client._testing__get_mit_i_d())
            .objects[0]
            .current.classes[0]  # type: ignore
            .uuid
        )
        await graphql_client._testing__create_address(
            employee, str(mit_id), mit_id_class, ituser=ad_ituser
        )

    return Account(
        employee=employee,
        ad_ituser=ad_ituser,
        fk_ituser=fk_ituser,
        object_guid=object_guid,
        fk_external_id=fk_external_id,
        user_key=user_key,
        name=f"{first_name} {last_name}",
    )


async def owners_of_ext_uuid(
    cache_sessionmaker: async_sessionmaker, ext_uuid: uuid.UUID
) -> list[uuid.UUID]:
    async with cache_sessionmaker() as session, session.begin():
        result = await session.execute(
            text('SELECT person FROM "user" WHERE "extUuid" = :ext'),
            {"ext": ext_uuid},
        )
        return [row[0] for row in result.all()]


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_concurrent_sync_person_no_duplicate_key_error(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
    caplog: pytest.LogCaptureFixture,
) -> None:
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    await graphql_client._testing__create_org_unit_root(
        root_uuid=root_uuid,
        name="Root",
        org_unit_type=org_unit_type,
    )
    org_unit = (
        await graphql_client._testing__create_org_unit(
            name="OU",
            parent=root_uuid,
            org_unit_type=org_unit_type,
        )
    ).uuid

    employee = (
        await graphql_client._testing__create_employee(
            first_name="Concurrent",
            last_name="User",
        )
    ).uuid

    engagement_type = (
        (await graphql_client._testing__get_engagement_type())
        .objects[0]
        .current.classes[0]  # type: ignore
        .uuid
    )
    job_function = (
        (await graphql_client._testing__get_job_function())
        .objects[0]
        .current.classes[0]  # type: ignore
    )
    eng = (
        await graphql_client._testing__create_engagement(
            org_unit, employee, engagement_type, job_function.uuid
        )
    ).uuid

    AD = (await graphql_client._testing__create_it_system("Active Directory")).uuid
    FK = (await graphql_client._testing__create_it_system("FK ORG")).uuid
    object_guid = uuid.uuid4()
    external_id = uuid.uuid4()
    await graphql_client._testing__create_it_user(
        AD, str(object_guid), employee, "CU", None, [eng]
    )
    await graphql_client._testing__create_it_user(
        FK, str(external_id), employee, str(object_guid), None, [eng]
    )

    # AMQP is disabled for this test, so the cache stays empty until our
    # POSTs run. We only need to wait for MO to be consistent enough that
    # /debug/person resolves the user.
    @retry()
    async def wait_for_mo() -> None:
        debug = (await test_client.get(f"/debug/person/{employee}")).json()
        assert isinstance(debug, list) and debug, f"MO not ready: {debug}"

    await wait_for_mo()

    # Gate every concurrent sync_person between its SELECT and its
    # INSERT/COMMIT, so all N transactions are guaranteed to have
    # observed an empty DB before any of them attempts to write.
    # Without this, asyncio.gather doesn't reliably reproduce the race
    # because one task can finish its commit before the next reads.
    #
    # The wait has a timeout so that when the production code is
    # properly serialized (by the advisory lock), the lone task at the
    # barrier proceeds after 1s, and subsequent tasks get
    # BrokenBarrierError and proceed too — no deadlock.
    barrier = asyncio.Barrier(CONCURRENT)
    real_fetch = person_module.fetch_users_from_db

    async def synchronized_fetch(session, p_uuid, *args, **kwargs):
        result = await real_fetch(session, p_uuid, *args, **kwargs)
        if p_uuid == employee:
            try:
                await asyncio.wait_for(barrier.wait(), timeout=1.0)
            except (asyncio.TimeoutError, asyncio.BrokenBarrierError):
                pass
        return result

    caplog.clear()
    with patch(
        "os2mo_rollekatalog.person.fetch_users_from_db",
        new=synchronized_fetch,
    ), caplog.at_level("INFO", logger="os2mo_rollekatalog.person"):
        responses = await asyncio.gather(
            *(test_client.post(f"/sync/person/{employee}") for _ in range(CONCURRENT)),
            return_exceptions=True,
        )

    for r in responses:
        assert not isinstance(r, BaseException), f"request raised: {r!r}"
        assert r.status_code == 200, f"request failed: {r.status_code} {r.text}"

    add_count = sum(1 for r in caplog.records if "Add new user" in r.getMessage())
    unchanged_count = sum(
        1 for r in caplog.records if "User unchanged" in r.getMessage()
    )
    assert add_count == 1, f"expected exactly one Add new user, got {add_count}"
    assert (
        unchanged_count == CONCURRENT - 1
    ), f"expected {CONCURRENT - 1} User unchanged, got {unchanged_count}"

    cached = (await test_client.get(f"/cache/person/{employee}")).json()
    assert cached == [
        {
            "extUuid": str(external_id),
            "nemloginUuid": None,
            "userId": "CU",
            "name": "Concurrent User",
            "email": None,
            "positions": [
                {
                    "name": job_function.name,
                    "orgUnitUuid": str(org_unit),
                }
            ],
        }
    ]


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_sync_handles_extuuid_change_with_same_nemlogin(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
    caplog: pytest.LogCaptureFixture,
) -> None:
    """FK external_id can change for the same AD account (e.g., FK Org
    re-registration). The next sync produces a to_remove + to_add for
    the same person carrying the same nemloginUuid. Without an explicit
    flush between the loops, SQLA's INSERT-before-DELETE order trips
    the unique constraint on nemloginUuid.
    """
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    await graphql_client._testing__create_org_unit_root(
        root_uuid=root_uuid, name="Root", org_unit_type=org_unit_type
    )
    org_unit = (
        await graphql_client._testing__create_org_unit(
            name="OU", parent=root_uuid, org_unit_type=org_unit_type
        )
    ).uuid
    employee = (
        await graphql_client._testing__create_employee(
            first_name="Swap", last_name="User"
        )
    ).uuid
    engagement_type = (
        (await graphql_client._testing__get_engagement_type())
        .objects[0]
        .current.classes[0]  # type: ignore
        .uuid
    )
    job_function = (
        (await graphql_client._testing__get_job_function())
        .objects[0]
        .current.classes[0]  # type: ignore
    )
    eng = (
        await graphql_client._testing__create_engagement(
            org_unit, employee, engagement_type, job_function.uuid
        )
    ).uuid

    AD = (await graphql_client._testing__create_it_system("Active Directory")).uuid
    FK = (await graphql_client._testing__create_it_system("FK ORG")).uuid
    object_guid = uuid.uuid4()
    fk_external_id_original = uuid.uuid4()
    fk_external_id_new = uuid.uuid4()
    mit_id = uuid.uuid4()

    ad_ituser = (
        await graphql_client._testing__create_it_user(
            AD, str(object_guid), employee, "SU", None, [eng]
        )
    ).uuid
    fk_ituser = (
        await graphql_client._testing__create_it_user(
            FK, str(fk_external_id_original), employee, str(object_guid), None, [eng]
        )
    ).uuid
    mit_id_class = (
        (await graphql_client._testing__get_mit_i_d())
        .objects[0]
        .current.classes[0]  # type: ignore
        .uuid
    )
    await graphql_client._testing__create_address(
        employee, str(mit_id), mit_id_class, ituser=ad_ituser
    )

    @retry()
    async def wait_for_mo() -> None:
        debug = (await test_client.get(f"/debug/person/{employee}")).json()
        assert isinstance(debug, list) and debug, f"MO not ready: {debug}"

    await wait_for_mo()

    # First sync — row gets created with the original FK external_id.
    response = await test_client.post(f"/sync/person/{employee}")
    assert response.status_code == 200, response.text
    cached = (await test_client.get(f"/cache/person/{employee}")).json()
    assert cached == [
        {
            "extUuid": str(fk_external_id_original),
            "nemloginUuid": str(mit_id),
            "userId": "SU",
            "name": "Swap User",
            "email": None,
            "positions": [
                {"name": job_function.name, "orgUnitUuid": str(org_unit)},
            ],
        }
    ]

    # Swap the FK ituser's external_id. AD ituser unchanged → same userId,
    # same nemloginUuid carry over, but extUuid flips.
    await graphql_client._testing__update_it_user_external_id(
        fk_ituser, str(fk_external_id_new), datetime.now()
    )

    @retry()
    async def wait_for_swap() -> None:
        debug = (await test_client.get(f"/debug/person/{employee}")).json()
        assert debug and debug[0]["extUuid"] == str(fk_external_id_new), debug

    await wait_for_swap()

    caplog.clear()
    with caplog.at_level("INFO", logger="os2mo_rollekatalog.person"):
        response = await test_client.post(f"/sync/person/{employee}")
        assert response.status_code == 200, response.text

    messages = [r.getMessage() for r in caplog.records]
    assert sum("Remove user" in m for m in messages) == 1, messages
    assert sum("Add new user" in m for m in messages) == 1, messages

    cached = (await test_client.get(f"/cache/person/{employee}")).json()
    assert cached == [
        {
            "extUuid": str(fk_external_id_new),
            "nemloginUuid": str(mit_id),
            "userId": "SU",
            "name": "Swap User",
            "email": None,
            "positions": [
                {"name": job_function.name, "orgUnitUuid": str(org_unit)},
            ],
        }
    ]


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_ituser_event_dedups_validities(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
) -> None:
    """A single ituser event with many validity periods triggers exactly
    one sync_person call per unique person.

    `get_uuids_for_it_user` queries `validities(start: null, end: null)`,
    so an ituser that has been updated multiple times yields multiple
    rows — but they almost always reference the same person. Without
    dedup the handler would call sync_person once per validity row,
    producing duplicate work and noisy logs (see the "User unchanged"
    spam reported in #70184). The handler must collapse the rows by
    person UUID before dispatching.
    """
    org_unit_type = (await graphql_client._testing__get_org_unit_type()).objects[0].uuid
    await graphql_client._testing__create_org_unit_root(
        root_uuid=root_uuid, name="Root", org_unit_type=org_unit_type
    )
    org_unit = (
        await graphql_client._testing__create_org_unit(
            name="OU", parent=root_uuid, org_unit_type=org_unit_type
        )
    ).uuid
    employee = (
        await graphql_client._testing__create_employee(
            first_name="Many", last_name="Validities"
        )
    ).uuid
    engagement_type = (
        (await graphql_client._testing__get_engagement_type())
        .objects[0]
        .current.classes[0]  # type: ignore
        .uuid
    )
    job_function = (
        (await graphql_client._testing__get_job_function())
        .objects[0]
        .current.classes[0]  # type: ignore
    )
    eng = (
        await graphql_client._testing__create_engagement(
            org_unit, employee, engagement_type, job_function.uuid
        )
    ).uuid

    AD = (await graphql_client._testing__create_it_system("Active Directory")).uuid
    FK = (await graphql_client._testing__create_it_system("FK ORG")).uuid
    object_guid = uuid.uuid4()
    external_id = uuid.uuid4()

    ad_ituser = (
        await graphql_client._testing__create_it_user(
            AD, str(object_guid), employee, "MV", None, [eng]
        )
    ).uuid
    await graphql_client._testing__create_it_user(
        FK, str(external_id), employee, str(object_guid), None, [eng]
    )

    # Bump the ituser repeatedly so it accumulates many validity rows.
    # MO collapses validities when nothing changes, so vary user_key each
    # round to force a new validity row per call.
    from datetime import datetime, timedelta

    for day in range(1, 6):
        await graphql_client._testing__update_it_user(
            ad_ituser,
            datetime.now() + timedelta(days=day),
            user_key=f"MV-{day}",
        )

    @retry()
    async def wait_for_validities() -> None:
        result = await graphql_client.get_uuids_for_it_user(ad_ituser)
        validities = [v for obj in result.objects for v in obj.validities]
        assert len(validities) >= 5, f"only {len(validities)} validities"

    await wait_for_validities()

    with patch("os2mo_rollekatalog.events.sync_person") as mock_sync:
        response = await test_client.post(
            "/ituser",
            json={"subject": str(ad_ituser), "priority": 10000},
        )
        assert response.status_code == 200, response.text

    # Exactly one sync_person call, for our employee — not one per validity.
    # sync_person(mo, periodic_sync, session, ad_key, fk_key, email_key,
    # mit_id_key, root_org_unit, person_uuid, ...) → person_uuid is positional 8.
    person_uuids = {call.args[8] for call in mock_sync.call_args_list}
    assert person_uuids == {employee}, person_uuids
    assert mock_sync.call_count == 1, mock_sync.call_args_list


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_sync_claims_extuuid_from_person_missing_in_mo(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
    cache_sessionmaker: async_sessionmaker,
    caplog: pytest.LogCaptureFixture,
) -> None:
    """The cached row holding our extUuid belongs to a person MO never heard of.

    This is what a database copy between environments leaves behind: the
    manually created employees were recreated with fresh UUIDs, while their FK
    ORG registration — and therefore extUuid — stayed the same. The old rows
    are unreachable, because no event will ever carry those person UUIDs again,
    so nothing would clean them up and the recreated employee would fail on the
    unique extUuid constraint on every single retry.
    """
    org_unit = await create_root_with_org_unit(graphql_client, root_uuid)
    engagement_type = (
        (await graphql_client._testing__get_engagement_type())
        .objects[0]
        .current.classes[0]  # type: ignore
        .uuid
    )
    job_function = (
        (await graphql_client._testing__get_job_function())
        .objects[0]
        .current.classes[0]  # type: ignore
    )
    account = await create_employee_with_account(
        graphql_client,
        org_unit,
        engagement_type,
        job_function.uuid,
        "Recreated",
        "User",
        "RU",
    )

    @retry()
    async def wait_for_mo() -> None:
        debug = (await test_client.get(f"/debug/person/{account.employee}")).json()
        assert isinstance(debug, list) and debug, f"MO not ready: {debug}"

    await wait_for_mo()

    response = await test_client.post(f"/sync/person/{account.employee}")
    assert response.status_code == 200, response.text
    assert await owners_of_ext_uuid(cache_sessionmaker, account.fk_external_id) == [
        account.employee
    ]

    # Reassign the row to a person UUID that does not exist in MO, the way a
    # copied database holds rows for employees this MO has never seen.
    ghost = uuid.uuid4()
    async with cache_sessionmaker() as session, session.begin():
        await session.execute(
            text('UPDATE "user" SET person = :ghost WHERE "extUuid" = :ext'),
            {"ghost": ghost, "ext": account.fk_external_id},
        )

    caplog.clear()
    with caplog.at_level("INFO", logger="os2mo_rollekatalog.person"):
        response = await test_client.post(f"/sync/person/{account.employee}")
    assert response.status_code == 200, response.text

    messages = [r.getMessage() for r in caplog.records]
    assert (
        sum("Claiming user from another person" in m for m in messages) == 1
    ), messages
    # The ghost row must not be mistaken for an up-to-date one. Which flavour
    # of write the reconciliation logs is not the point — the state assertions
    # below are — so don't pin it here.
    assert not any("User unchanged" in m for m in messages), messages

    # The ghost row is gone and the extUuid belongs to the employee MO knows.
    assert await owners_of_ext_uuid(cache_sessionmaker, account.fk_external_id) == [
        account.employee
    ]
    assert (await test_client.get(f"/cache/person/{ghost}")).json() == []
    assert (await test_client.get(f"/cache/person/{account.employee}")).json() == [
        {
            "extUuid": str(account.fk_external_id),
            "nemloginUuid": None,
            "userId": "RU",
            "name": "Recreated User",
            "email": None,
            "positions": [
                {"name": job_function.name, "orgUnitUuid": str(org_unit)},
            ],
        }
    ]


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_sync_claims_nemlogin_uuid_from_person_missing_in_mo(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
    cache_sessionmaker: async_sessionmaker,
    caplog: pytest.LogCaptureFixture,
) -> None:
    """Same as above, but the stale row collides on nemloginUuid instead.

    nemloginUuid is unique too, so a recreated employee carrying the same MitID
    is blocked by the stale row even when its extUuid is free.
    """
    org_unit = await create_root_with_org_unit(graphql_client, root_uuid)
    engagement_type = (
        (await graphql_client._testing__get_engagement_type())
        .objects[0]
        .current.classes[0]  # type: ignore
        .uuid
    )
    job_function = (
        (await graphql_client._testing__get_job_function())
        .objects[0]
        .current.classes[0]  # type: ignore
    )
    mit_id = uuid.uuid4()
    account = await create_employee_with_account(
        graphql_client,
        org_unit,
        engagement_type,
        job_function.uuid,
        "Mit",
        "User",
        "MU",
        mit_id=mit_id,
    )

    @retry()
    async def wait_for_mo() -> None:
        debug = (await test_client.get(f"/debug/person/{account.employee}")).json()
        assert debug and debug[0]["nemloginUuid"] == str(mit_id), debug

    await wait_for_mo()

    response = await test_client.post(f"/sync/person/{account.employee}")
    assert response.status_code == 200, response.text

    # Strand the row under an unknown person and free up its extUuid, so that
    # nemloginUuid is the only key left to collide on.
    ghost = uuid.uuid4()
    stale_ext_uuid = uuid.uuid4()
    async with cache_sessionmaker() as session, session.begin():
        await session.execute(
            text(
                'UPDATE "user" SET person = :ghost, "extUuid" = :stale '
                'WHERE "extUuid" = :ext'
            ),
            {"ghost": ghost, "stale": stale_ext_uuid, "ext": account.fk_external_id},
        )

    caplog.clear()
    with caplog.at_level("INFO", logger="os2mo_rollekatalog.person"):
        response = await test_client.post(f"/sync/person/{account.employee}")
    assert response.status_code == 200, response.text

    messages = [r.getMessage() for r in caplog.records]
    assert (
        sum("Claiming user from another person" in m for m in messages) == 1
    ), messages

    assert await owners_of_ext_uuid(cache_sessionmaker, stale_ext_uuid) == []
    assert (await test_client.get(f"/cache/person/{account.employee}")).json() == [
        {
            "extUuid": str(account.fk_external_id),
            "nemloginUuid": str(mit_id),
            "userId": "MU",
            "name": "Mit User",
            "email": None,
            "positions": [
                {"name": job_function.name, "orgUnitUuid": str(org_unit)},
            ],
        }
    ]


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_sync_claims_extuuid_handed_over_to_another_employee(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
    cache_sessionmaker: async_sessionmaker,
    caplog: pytest.LogCaptureFixture,
) -> None:
    """An FK ORG registration moves to another employee that MO still knows.

    Shared accounts (e.g. "Vikarbruger - X") get re-registered on whoever uses
    them next. Only the new owner gets an event, so the previous owner's cached
    row lingers and blocks the insert. Unlike the cases above this needs no
    surgery on the cache — plain MO mutations reproduce it.
    """
    org_unit = await create_root_with_org_unit(graphql_client, root_uuid)
    engagement_type = (
        (await graphql_client._testing__get_engagement_type())
        .objects[0]
        .current.classes[0]  # type: ignore
        .uuid
    )
    job_function = (
        (await graphql_client._testing__get_job_function())
        .objects[0]
        .current.classes[0]  # type: ignore
    )
    previous = await create_employee_with_account(
        graphql_client,
        org_unit,
        engagement_type,
        job_function.uuid,
        "Previous",
        "Owner",
        "PO",
    )
    new = await create_employee_with_account(
        graphql_client,
        org_unit,
        engagement_type,
        job_function.uuid,
        "New",
        "Owner",
        "NO",
    )

    @retry()
    async def wait_for_mo() -> None:
        for employee in (previous.employee, new.employee):
            debug = (await test_client.get(f"/debug/person/{employee}")).json()
            assert isinstance(debug, list) and debug, f"MO not ready: {debug}"

    await wait_for_mo()

    for employee in (previous.employee, new.employee):
        response = await test_client.post(f"/sync/person/{employee}")
        assert response.status_code == 200, response.text

    # Hand the FK ORG registration over: the new owner's account now resolves
    # to the extUuid the previous owner's cached row still holds.
    await graphql_client._testing__update_it_user_external_id(
        new.fk_ituser, str(previous.fk_external_id), datetime.now()
    )

    @retry()
    async def wait_for_handover() -> None:
        debug = (await test_client.get(f"/debug/person/{new.employee}")).json()
        assert debug and debug[0]["extUuid"] == str(previous.fk_external_id), debug

    await wait_for_handover()

    caplog.clear()
    with caplog.at_level("INFO", logger="os2mo_rollekatalog.person"):
        response = await test_client.post(f"/sync/person/{new.employee}")
    assert response.status_code == 200, response.text

    messages = [r.getMessage() for r in caplog.records]
    assert (
        sum("Claiming user from another person" in m for m in messages) == 1
    ), messages

    assert await owners_of_ext_uuid(cache_sessionmaker, previous.fk_external_id) == [
        new.employee
    ]
    assert (await test_client.get(f"/cache/person/{previous.employee}")).json() == []
    assert (await test_client.get(f"/cache/person/{new.employee}")).json() == [
        {
            "extUuid": str(previous.fk_external_id),
            "nemloginUuid": None,
            "userId": "NO",
            "name": "New Owner",
            "email": None,
            "positions": [
                {"name": job_function.name, "orgUnitUuid": str(org_unit)},
            ],
        }
    ]
