# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Which Rollekatalog users a person produces."""

import uuid
from collections.abc import Awaitable
from collections.abc import Callable
from datetime import datetime
from datetime import timedelta

import pytest
from fastramqpi.pytest_util import retry
from httpx import AsyncClient

from os2mo_rollekatalog.autogenerated_graphql_client import EmployeeCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient
from os2mo_rollekatalog.autogenerated_graphql_client import ITUserUpdateInput
from os2mo_rollekatalog.autogenerated_graphql_client import RAValidityInput


@pytest.mark.integration_test
async def test_person_and_accounts_are_synced(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
    mit_id_employee: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_engagement: Callable[..., Awaitable[uuid.UUID]],
    create_address: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """A person with two AD accounts produces one user per account, and a
    MitID address linked to one account becomes only that user's
    nemloginUuid.

    Runs through the real event listeners, covering the whole event-driven
    path for persons.
    """
    await create_org_unit(name="Root", uuid=root_uuid)
    unit = await create_org_unit(name="Unit", parent=root_uuid)
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Anders", surname="And")
        )
    ).uuid
    eng = await create_engagement(org_unit=unit, person=employee)
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    guid_1, external_1 = uuid.uuid4(), uuid.uuid4()
    guid_2, external_2 = uuid.uuid4(), uuid.uuid4()
    mit_id = uuid.uuid4()
    ituser_1 = await create_ituser(
        itsystem=AD,
        external_id=str(guid_1),
        person=employee,
        user_key="AA",
        engagements=[eng],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_1),
        person=employee,
        user_key=str(guid_1),
        engagements=[eng],
    )
    await create_ituser(
        itsystem=AD,
        external_id=str(guid_2),
        person=employee,
        user_key="AA2",
        engagements=[eng],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_2),
        person=employee,
        user_key=str(guid_2),
        engagements=[eng],
    )
    await create_address(
        person=employee,
        value=str(mit_id),
        address_type=mit_id_employee,
        ituser=ituser_1,
    )

    @retry()
    async def verify_users() -> None:
        users = (await test_client.get(f"/cache/person/{employee}")).json()
        assert sorted(users, key=lambda u: u["userId"]) == [
            {
                "extUuid": str(external_1),
                "nemloginUuid": str(mit_id),
                "userId": "AA",
                "name": "Anders And",
                "email": None,
                "positions": [{"name": "Jurist", "orgUnitUuid": str(unit)}],
                "functions": [],
            },
            {
                "extUuid": str(external_2),
                "nemloginUuid": None,
                "userId": "AA2",
                "name": "Anders And",
                "email": None,
                "positions": [{"name": "Jurist", "orgUnitUuid": str(unit)}],
                "functions": [],
            },
        ]

    await verify_users()


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_person_without_sam_account_is_not_synced(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
) -> None:
    """A person with no AD account at all is not synced."""
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Sam", surname="Mangler")
        )
    ).uuid

    await trigger_event("person", employee)

    assert (await test_client.get(f"/cache/person/{employee}")).json() == []
    assert (await test_client.get(f"/debug/person/{employee}")).json() == {
        "error": "No SAM Account"
    }


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_person_without_resolvable_fk_account_is_not_synced(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """An AD account whose FK-org pairing carries no external_id resolves to
    no extUuid, so the person is not synced."""
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Joakim", surname="von And")
        )
    ).uuid
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid = uuid.uuid4()
    await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="JvA",
        engagements=[],
    )
    await create_ituser(
        itsystem=FK,
        external_id="",
        person=employee,
        user_key=str(object_guid),
        engagements=[],
    )

    await trigger_event("person", employee)

    assert (await test_client.get(f"/cache/person/{employee}")).json() == []


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_ituser_scopes_positions_to_its_engagements(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_engagement: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """A user gets one position per engagement on its AD account, and
    shrinking the account's engagements shrinks the positions."""
    await create_org_unit(name="Root", uuid=root_uuid)
    unit_a = await create_org_unit(name="Unit A", parent=root_uuid)
    unit_b = await create_org_unit(name="Unit B", parent=root_uuid)
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Fætter", surname="Højben")
        )
    ).uuid
    eng_a = await create_engagement(org_unit=unit_a, person=employee)
    eng_b = await create_engagement(org_unit=unit_b, person=employee)
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid, external_id = uuid.uuid4(), uuid.uuid4()
    ad_ituser = await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="FH",
        engagements=[eng_a, eng_b],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
        engagements=[eng_a, eng_b],
    )

    await trigger_event("person", employee)
    user = (await test_client.get(f"/cache/person/{employee}")).json()[0]
    assert sorted(p["orgUnitUuid"] for p in user["positions"]) == sorted(
        [str(unit_a), str(unit_b)]
    )

    # Scope the AD account down to one engagement.
    await graphql_client._testing__update_it_user(
        input=ITUserUpdateInput(
            uuid=ad_ituser,
            engagements=[eng_a],
            validity=RAValidityInput(from_=datetime.now()),
        )
    )

    await trigger_event("person", employee)
    user = (await test_client.get(f"/cache/person/{employee}")).json()[0]
    assert [p["orgUnitUuid"] for p in user["positions"]] == [str(unit_a)]


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_future_account_is_synced(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_engagement: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """An AD account that only becomes valid in the future is synced ahead of
    its first day."""
    await create_org_unit(name="Root", uuid=root_uuid)
    unit = await create_org_unit(name="Unit", parent=root_uuid)
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Fætter", surname="Højben")
        )
    ).uuid
    eng = await create_engagement(org_unit=unit, person=employee)
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid, external_id = uuid.uuid4(), uuid.uuid4()
    await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="FH",
        engagements=[eng],
        from_=datetime.now() + timedelta(days=365),
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
        engagements=[eng],
    )

    await trigger_event("person", employee)

    assert (await test_client.get(f"/cache/person/{employee}")).json() == [
        {
            "extUuid": str(external_id),
            "nemloginUuid": None,
            "userId": "FH",
            "name": "Fætter Højben",
            "email": None,
            "positions": [{"name": "Jurist", "orgUnitUuid": str(unit)}],
            "functions": [],
        }
    ]


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_future_account_rename_does_not_affect_current(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_engagement: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """A future-dated user_key change on an AD account does not change the
    userId synced today."""
    await create_org_unit(name="Root", uuid=root_uuid)
    unit = await create_org_unit(name="Unit", parent=root_uuid)
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Fedt", surname="mule")
        )
    ).uuid
    eng = await create_engagement(org_unit=unit, person=employee)
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid, external_id = uuid.uuid4(), uuid.uuid4()
    ad_ituser = await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="FM",
        engagements=[eng],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
        engagements=[eng],
    )
    await graphql_client._testing__update_it_user(
        input=ITUserUpdateInput(
            uuid=ad_ituser,
            user_key="Updated name",
            validity=RAValidityInput(from_=datetime.now() + timedelta(days=365)),
        )
    )

    await trigger_event("person", employee)

    user = (await test_client.get(f"/cache/person/{employee}")).json()[0]
    assert user["userId"] == "FM"
