# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""IT-users are synced for engagements valid now (Nutid) or in the future
(Fremtid). Previously only engagements valid right now produced a position."""

import uuid
from datetime import datetime
from datetime import timedelta

import pytest
from httpx import AsyncClient
from more_itertools import one

from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_future_engagement_is_synced(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
) -> None:
    """A person whose only engagement starts in the future is synced with a
    position."""
    # Arrange: a unit, and a person whose only engagement starts in a year.
    org_unit_type = one(
        (await graphql_client._testing__get_org_unit_type()).objects
    ).uuid
    await graphql_client._testing__create_org_unit_root(
        root_uuid=root_uuid, name="Root", org_unit_type=org_unit_type
    )
    org_unit = (
        await graphql_client._testing__create_org_unit(
            name="OU", parent=root_uuid, org_unit_type=org_unit_type
        )
    ).uuid
    employee = (
        await graphql_client._testing__create_employee(
            first_name="Fætter", last_name="Højben"
        )
    ).uuid
    engagement_type = one(
        one(
            (await graphql_client._testing__get_engagement_type()).objects
        ).current.classes  # type: ignore
    ).uuid
    job_function = one(
        one((await graphql_client._testing__get_job_function()).objects).current.classes  # type: ignore
    )
    # Engagement that only becomes valid in a year.
    future = datetime.now() + timedelta(days=365)
    eng = (
        await graphql_client._testing__create_engagement(
            org_unit, employee, engagement_type, job_function.uuid, future
        )
    ).uuid

    AD = (await graphql_client._testing__create_it_system("Active Directory")).uuid
    FK = (await graphql_client._testing__create_it_system("FK ORG")).uuid
    object_guid = uuid.uuid4()
    external_id = uuid.uuid4()
    await graphql_client._testing__create_it_user(
        AD, str(object_guid), employee, "FH", None, [eng]
    )
    await graphql_client._testing__create_it_user(
        FK, str(external_id), employee, str(object_guid), None, [eng]
    )

    # Act.
    response = await test_client.post(f"/sync/person/{employee}")
    assert response.status_code == 200, response.text

    # Assert: the user is synced with a position in the future engagement's unit.
    assert (await test_client.get(f"/cache/person/{employee}")).json() == [
        {
            "extUuid": str(external_id),
            "nemloginUuid": None,
            "userId": "FH",
            "name": "Fætter Højben",
            "email": None,
            "positions": [{"name": job_function.name, "orgUnitUuid": str(org_unit)}],
        }
    ]


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_current_and_future_engagements_both_synced(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
) -> None:
    """A person with one current and one future engagement gets both positions."""
    # Arrange: two units, and a person with a current engagement in one and a
    # future engagement in the other.
    org_unit_type = one(
        (await graphql_client._testing__get_org_unit_type()).objects
    ).uuid
    await graphql_client._testing__create_org_unit_root(
        root_uuid=root_uuid, name="Root", org_unit_type=org_unit_type
    )
    unit_a = (
        await graphql_client._testing__create_org_unit(
            name="Unit A", parent=root_uuid, org_unit_type=org_unit_type
        )
    ).uuid
    unit_b = (
        await graphql_client._testing__create_org_unit(
            name="Unit B", parent=root_uuid, org_unit_type=org_unit_type
        )
    ).uuid
    employee = (
        await graphql_client._testing__create_employee(
            first_name="Anders", last_name="And"
        )
    ).uuid
    engagement_type = one(
        one(
            (await graphql_client._testing__get_engagement_type()).objects
        ).current.classes  # type: ignore
    ).uuid
    job_function = one(
        one((await graphql_client._testing__get_job_function()).objects).current.classes  # type: ignore
    )
    current_eng = (
        await graphql_client._testing__create_engagement(
            unit_a, employee, engagement_type, job_function.uuid
        )
    ).uuid
    future = datetime.now() + timedelta(days=365)
    future_eng = (
        await graphql_client._testing__create_engagement(
            unit_b, employee, engagement_type, job_function.uuid, future
        )
    ).uuid

    AD = (await graphql_client._testing__create_it_system("Active Directory")).uuid
    FK = (await graphql_client._testing__create_it_system("FK ORG")).uuid
    object_guid = uuid.uuid4()
    external_id = uuid.uuid4()
    await graphql_client._testing__create_it_user(
        AD, str(object_guid), employee, "AA", None, [current_eng, future_eng]
    )
    await graphql_client._testing__create_it_user(
        FK,
        str(external_id),
        employee,
        str(object_guid),
        None,
        [current_eng, future_eng],
    )

    # Act.
    response = await test_client.post(f"/sync/person/{employee}")
    assert response.status_code == 200, response.text

    # Assert: both engagements produce a position.
    cached = (await test_client.get(f"/cache/person/{employee}")).json()
    positions = one(cached)["positions"]
    assert sorted(positions, key=lambda p: p["orgUnitUuid"]) == sorted(
        [
            {"name": job_function.name, "orgUnitUuid": str(unit_a)},
            {"name": job_function.name, "orgUnitUuid": str(unit_b)},
        ],
        key=lambda p: p["orgUnitUuid"],
    )
