# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import uuid
from collections.abc import Awaitable
from collections.abc import Callable
from datetime import datetime, timedelta

import pytest
from fastramqpi.pytest_util import retry
from httpx import AsyncClient

from os2mo_rollekatalog.autogenerated_graphql_client import ClassCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import EmployeeCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient
from os2mo_rollekatalog.autogenerated_graphql_client import ITUserUpdateInput
from os2mo_rollekatalog.autogenerated_graphql_client import OrganisationUnitUpdateInput
from os2mo_rollekatalog.autogenerated_graphql_client import RAValidityInput
from tests.integration.conftest import SEED_RA_VALIDITY
from tests.integration.conftest import SEED_VALIDITY


@pytest.mark.integration_test
async def test_dummy() -> None:
    return


@pytest.mark.integration_test
async def test_too_much(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
    exclude_org_unit_level: uuid.UUID,
    external_roots: list[str],
    org_unit_level_facet: uuid.UUID,
    mit_id_employee: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_engagement: Callable[..., Awaitable[uuid.UUID]],
    create_manager: Callable[..., Awaitable[uuid.UUID]],
    create_address: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    # Create org hierarchy
    exclude_org_unit_level_uuid = (
        await graphql_client._testing__create_class(
            input=ClassCreateInput(
                user_key="Udgået",
                name="Udgået",
                facet_uuid=org_unit_level_facet,
                uuid=exclude_org_unit_level,
                validity=SEED_VALIDITY,
            )
        )
    ).uuid
    await create_org_unit(name="Root", uuid=root_uuid)
    layer1_1 = await create_org_unit(name="Layer 1 - Unit 1", parent=root_uuid)
    layer1_2 = await create_org_unit(name="Layer 1 - Unit 2", parent=root_uuid)
    layer2_1 = await create_org_unit(name="Layer 2 - Unit 1", parent=layer1_2)
    layer3_1 = await create_org_unit(name="Layer 3 - Unit 1", parent=layer2_1)
    layer1_3 = await create_org_unit(
        name="Layer 1 - Unit 3",
        parent=root_uuid,
        org_unit_level=exclude_org_unit_level_uuid,
    )
    layer2_3 = await create_org_unit(name="Layer 2 - Unit 3", parent=layer1_3)
    external_root = await create_org_unit(name="External root", uuid=external_roots[0])
    external_layer1_1 = await create_org_unit(
        name="External Layer 1 - Unit 1", parent=external_root
    )

    @retry()
    async def validate_hierarchy() -> None:
        assert (await test_client.get(f"/cache/org_unit/{root_uuid}")).json() == {
            "uuid": str(root_uuid),
            "name": "Root",
            "parentOrgUnitUuid": None,
            "manager": None,
            "klePerforming": [],
            "kleInterest": [],
        }
        assert (await test_client.get(f"/cache/org_unit/{layer1_1}")).json() == {
            "uuid": str(layer1_1),
            "name": "Layer 1 - Unit 1",
            "parentOrgUnitUuid": str(root_uuid),
            "manager": None,
            "klePerforming": [],
            "kleInterest": [],
        }
        assert (await test_client.get(f"/cache/org_unit/{layer1_2}")).json() == {
            "uuid": str(layer1_2),
            "name": "Layer 1 - Unit 2",
            "parentOrgUnitUuid": str(root_uuid),
            "manager": None,
            "klePerforming": [],
            "kleInterest": [],
        }
        assert (await test_client.get(f"/cache/org_unit/{layer2_1}")).json() == {
            "uuid": str(layer2_1),
            "name": "Layer 2 - Unit 1",
            "parentOrgUnitUuid": str(layer1_2),
            "manager": None,
            "klePerforming": [],
            "kleInterest": [],
        }
        assert (await test_client.get(f"/cache/org_unit/{layer3_1}")).json() == {
            "uuid": str(layer3_1),
            "name": "Layer 3 - Unit 1",
            "parentOrgUnitUuid": str(layer2_1),
            "manager": None,
            "klePerforming": [],
            "kleInterest": [],
        }
        assert (await test_client.get(f"/cache/org_unit/{layer1_3}")).json() is None
        assert (await test_client.get(f"/cache/org_unit/{layer2_3}")).json() is None
        assert (await test_client.get(f"/cache/org_unit/{external_root}")).json() == {
            "uuid": str(external_root),
            "name": "External root",
            "parentOrgUnitUuid": str(root_uuid),
            "manager": None,
            "klePerforming": [],
            "kleInterest": [],
        }
        assert (
            await test_client.get(f"/cache/org_unit/{external_layer1_1}")
        ).json() == {
            "uuid": str(external_layer1_1),
            "name": "External Layer 1 - Unit 1",
            "parentOrgUnitUuid": str(external_root),
            "manager": None,
            "klePerforming": [],
            "kleInterest": [],
        }

    await validate_hierarchy()

    await graphql_client._testing__update_org_unit(
        input=OrganisationUnitUpdateInput(
            uuid=layer1_1, name="New Name", validity=SEED_RA_VALIDITY
        )
    )

    @retry()
    async def observe_name_change() -> None:
        assert (await test_client.get(f"/cache/org_unit/{layer1_1}")).json() == {
            "uuid": str(layer1_1),
            "name": "New Name",
            "parentOrgUnitUuid": str(root_uuid),
            "manager": None,
            "klePerforming": [],
            "kleInterest": [],
        }

    await observe_name_change()

    # Create employees
    anders_and = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Anders", surname="And")
        )
    ).uuid
    fedtmule = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Fedt", surname="mule")
        )
    ).uuid
    joakim = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Joakim", surname="von And")
        )
    ).uuid
    user_without_sam_account = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Sam", surname="Mangler")
        )
    ).uuid
    fætter_højben = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Fætter", surname="Højben")
        )
    ).uuid

    # Create engagements ("positions"). Note that Joakim does not work.
    joakim_eng = await create_engagement(org_unit=layer2_1, person=joakim)
    anders_and_eng = await create_engagement(org_unit=layer1_2, person=anders_and)
    fedtmule_eng = await create_engagement(org_unit=external_layer1_1, person=fedtmule)
    fætter_eng_1 = await create_engagement(org_unit=layer3_1, person=fætter_højben)
    fætter_eng_2 = await create_engagement(org_unit=layer1_2, person=fætter_højben)

    # Create Active Directory IT system and users
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")

    joakim_object_guid = uuid.uuid4()
    await create_ituser(
        itsystem=AD,
        external_id=str(joakim_object_guid),
        person=joakim,
        user_key="JvA",
        engagements=[joakim_eng],
    )
    await create_ituser(
        itsystem=FK,
        external_id="",
        person=joakim,
        user_key=str(joakim_object_guid),
        engagements=[joakim_eng],
    )

    anders_object_guid = uuid.uuid4()
    anders_external_id = uuid.uuid4()
    anders_object_guid_2 = uuid.uuid4()
    anders_external_id_2 = uuid.uuid4()
    anders_mit_id = uuid.uuid4()

    anders_ituser = await create_ituser(
        itsystem=AD,
        external_id=str(anders_object_guid),
        person=anders_and,
        user_key="AA",
        engagements=[anders_and_eng],
    )
    await create_address(
        person=anders_and,
        value=str(anders_mit_id),
        address_type=mit_id_employee,
        ituser=anders_ituser,
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(anders_external_id),
        person=anders_and,
        user_key=str(anders_object_guid),
        engagements=[anders_and_eng],
    )

    anders_ituser_2 = await create_ituser(
        itsystem=AD,
        external_id=str(anders_object_guid_2),
        person=anders_and,
        user_key="AA2",
        engagements=[anders_and_eng],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(anders_external_id_2),
        person=anders_and,
        user_key=str(anders_object_guid_2),
        engagements=[anders_and_eng],
    )

    fedtmule_object_guid = uuid.uuid4()
    fedtmule_external_id = uuid.uuid4()
    fedtmule_ad_ituser = await create_ituser(
        itsystem=AD,
        external_id=str(fedtmule_object_guid),
        person=fedtmule,
        user_key="FM",
        engagements=[fedtmule_eng],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(fedtmule_external_id),
        person=fedtmule,
        user_key=str(fedtmule_object_guid),
        engagements=[fedtmule_eng],
    )
    await graphql_client._testing__update_it_user(
        input=ITUserUpdateInput(
            uuid=fedtmule_ad_ituser,
            user_key="Updated name",
            validity=RAValidityInput(from_=datetime.now() + timedelta(days=365)),
        )
    )

    fætter_object_guid = uuid.uuid4()
    fætter_external_id = uuid.uuid4()
    fætter_højben_ad_ituser = await create_ituser(
        itsystem=AD,
        external_id=str(fætter_object_guid),
        person=fætter_højben,
        user_key="FH",
        engagements=[fætter_eng_1, fætter_eng_2],
        from_=datetime.now() + timedelta(days=365),
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(fætter_external_id),
        person=fætter_højben,
        user_key=str(fætter_object_guid),
        engagements=[fætter_eng_1, fætter_eng_2],
    )

    @retry()
    async def verify_users() -> None:
        assert (
            await test_client.get(f"/debug/person/{user_without_sam_account}")
        ).json() == {"error": "No SAM Account"}
        assert (await test_client.get(f"/debug/person/{joakim}")).json() == []

        anders_response = (await test_client.get(f"/cache/person/{anders_and}")).json()
        anders_response = sorted(anders_response, key=lambda u: u["userId"])
        assert anders_response == [
            {
                "extUuid": str(anders_external_id),
                "nemloginUuid": str(anders_mit_id),
                "userId": "AA",
                "name": "Anders And",
                "email": None,
                "positions": [
                    {
                        "name": "Jurist",
                        "orgUnitUuid": str(layer1_2),
                    }
                ],
            },
            {
                "extUuid": str(anders_external_id_2),
                "nemloginUuid": None,
                "userId": "AA2",
                "name": "Anders And",
                "email": None,
                "positions": [
                    {
                        "name": "Jurist",
                        "orgUnitUuid": str(layer1_2),
                    }
                ],
            },
        ]
        assert (await test_client.get(f"/cache/person/{fedtmule}")).json() == [
            {
                "extUuid": str(fedtmule_external_id),
                "nemloginUuid": None,
                "userId": "FM",
                "name": "Fedt mule",
                "email": None,
                "positions": [
                    {
                        "name": "Jurist",
                        "orgUnitUuid": str(external_layer1_1),
                    }
                ],
            }
        ]

        fh_response = (await test_client.get(f"/cache/person/{fætter_højben}")).json()
        for user in fh_response:
            user["positions"] = sorted(
                user["positions"], key=lambda p: p["orgUnitUuid"]
            )
        expected_fh_response = [
            {
                "extUuid": str(fætter_external_id),
                "nemloginUuid": None,
                "userId": "FH",
                "name": "Fætter Højben",
                "email": None,
                "positions": sorted(
                    [
                        {"name": "Jurist", "orgUnitUuid": str(layer1_2)},
                        {"name": "Jurist", "orgUnitUuid": str(layer3_1)},
                    ],
                    key=lambda p: p["orgUnitUuid"],
                ),
            }
        ]
        assert fh_response == expected_fh_response

    await verify_users()

    await graphql_client._testing__update_it_user(
        input=ITUserUpdateInput(
            uuid=fætter_højben_ad_ituser,
            engagements=[fætter_eng_1],
            validity=RAValidityInput(from_=datetime.now()),
        )
    )

    @retry()
    async def verify_users_post_update() -> None:
        assert (await test_client.get(f"/cache/person/{fætter_højben}")).json() == [
            {
                "extUuid": str(fætter_external_id),
                "nemloginUuid": None,
                "userId": "FH",
                "name": "Fætter Højben",
                "email": None,
                "positions": [
                    {
                        "name": "Jurist",
                        "orgUnitUuid": str(layer3_1),
                    }
                ],
            }
        ]

    await verify_users_post_update()

    # Create manager WITHOUT extUuid (Should be skipped)
    await create_manager(person=joakim, org_unit=layer2_1)
    await create_manager(person=anders_and, org_unit=layer1_2)

    @retry()
    async def verify_manager() -> None:
        assert (await test_client.get(f"/cache/org_unit/{layer2_1}")).json() == {
            "uuid": str(layer2_1),
            "name": "Layer 2 - Unit 1",
            "parentOrgUnitUuid": str(layer1_2),
            "manager": None,
            "klePerforming": [],
            "kleInterest": [],
        }
        # Anders has two SAM accounts; manager resolution sorts itusers
        # by str(uuid) and picks the first, so mirror that here.
        if str(anders_ituser) < str(anders_ituser_2):
            expected_manager_extuuid = anders_external_id
            expected_manager_userid = "AA"
        else:
            expected_manager_extuuid = anders_external_id_2
            expected_manager_userid = "AA2"
        assert (await test_client.get(f"/cache/org_unit/{layer1_2}")).json() == {
            "uuid": str(layer1_2),
            "name": "Layer 1 - Unit 2",
            "parentOrgUnitUuid": str(root_uuid),
            "manager": {
                "id": 1,
                "org_unit_id": 9,
                "uuid": str(expected_manager_extuuid),
                "userId": expected_manager_userid,
            },
            "klePerforming": [],
            "kleInterest": [],
        }

    await verify_manager()

    # Move org out of synced tree. This should also remove our users from cache
    await graphql_client._testing__update_org_unit(
        input=OrganisationUnitUpdateInput(
            uuid=layer1_2, parent=None, validity=SEED_RA_VALIDITY
        )
    )
    await graphql_client._testing__update_org_unit(
        input=OrganisationUnitUpdateInput(
            uuid=external_layer1_1, parent=None, validity=SEED_RA_VALIDITY
        )
    )

    @retry()
    async def verify_removal() -> None:
        assert (await test_client.get(f"/cache/person/{joakim}")).json() == []
        assert (await test_client.get(f"/cache/person/{anders_and}")).json() == []
        assert (await test_client.get(f"/cache/person/{fedtmule}")).json() == []
        assert (await test_client.get(f"/cache/person/{fætter_højben}")).json() == []
        assert (await test_client.get(f"/cache/org_unit/{layer1_2}")).json() is None
        assert (await test_client.get(f"/cache/org_unit/{layer2_1}")).json() is None
        assert (await test_client.get(f"/cache/org_unit/{layer3_1}")).json() is None
        assert (
            await test_client.get(f"/cache/org_unit/{external_layer1_1}")
        ).json() is None

    await verify_removal()
