# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import pytest
from fastapi.testclient import TestClient
from fastramqpi.pytest_util import retry

from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient


@pytest.mark.integration_test
async def test_version(
    test_client: TestClient,
    graphql_client: GraphQLClient,
) -> None:
    version = await graphql_client.get_version()

    @retry()
    async def verify() -> None:
        assert version.mo_version == "36.7.2"

    await verify()


@pytest.mark.integration_test
async def test_greeting(
    test_client: TestClient,
    graphql_client: GraphQLClient,
) -> None:
    r = test_client.get("/hello")
    assert r.json() == "World!"
