# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Tillidsfunktioner: the function catalog and each person's functions."""

import json
import uuid
from collections.abc import Awaitable
from collections.abc import Callable

import pytest
from fastapi import FastAPI
from httpx import AsyncClient
from httpx import MockTransport
from httpx import Request
from httpx import Response
from more_itertools import one
from pytest import MonkeyPatch

from os2mo_rollekatalog import rollekatalog
from os2mo_rollekatalog.app import create_app
from os2mo_rollekatalog.autogenerated_graphql_client import ClassUpdateInput
from os2mo_rollekatalog.autogenerated_graphql_client import EmployeeCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient
from os2mo_rollekatalog.rollekatalog import RollekatalogClient
from tests.integration.conftest import SEED_VALIDITY


@pytest.fixture
async def app(
    monkeypatch: MonkeyPatch,
    root_uuid: uuid.UUID,
    exclude_org_unit_level: uuid.UUID,
    external_roots: list[uuid.UUID],
) -> FastAPI:
    """The conftest app with SYNC_FUNCTIONS enabled and a fake Rollekatalog.

    The fake implements /api/v2/function/sync the way Rollekatalog does:
    functions are looked up by the UUID we send, then by name, and otherwise
    created with a UUID Rollekatalog generates itself.
    """
    functions_in_rk: dict[str, str] = {}

    def handler(request: Request) -> Response:
        if request.url.path != "/api/v2/function/sync":
            return Response(200, json=[])
        result = []
        for function in json.loads(request.content):
            rk_uuid = function.get("uuid")
            if rk_uuid not in functions_in_rk:
                by_name = {name: u for u, name in functions_in_rk.items()}
                rk_uuid = by_name.get(function["name"], str(uuid.uuid4()))
            functions_in_rk[rk_uuid] = function["name"]
            result.append({"name": function["name"], "uuid": rk_uuid})
        return Response(200, json=result)

    def fake_client(*args: object, **kwargs: object) -> RollekatalogClient:
        return RollekatalogClient(
            AsyncClient(base_url="http://example.org", transport=MockTransport(handler))
        )

    monkeypatch.setattr(rollekatalog, "create_authenticated_client", fake_client)
    monkeypatch.setenv("ROLLEKATALOG_URL", "http://example.org")
    monkeypatch.setenv("API_KEY", "dummy")
    monkeypatch.setenv("ROOT_ORG_UNIT", str(root_uuid))
    monkeypatch.setenv("SYNC_FUNCTIONS", "true")
    monkeypatch.setenv(
        "AD_ITSYSTEM_USER_KEYS", json.dumps(["Active Directory", "Skole-AD"])
    )
    monkeypatch.setenv("FK_ITSYSTEM_USER_KEY", "FK ORG")
    monkeypatch.setenv("EXCLUDE_ORG_UNIT_LEVEL", str(exclude_org_unit_level))
    monkeypatch.setenv(
        "EXTERNAL_ROOTS", json.dumps([str(root) for root in external_roots])
    )

    return create_app()


async def create_person_with_sam_account(
    graphql_client: GraphQLClient,
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
) -> uuid.UUID:
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Tillids", surname="Fuld")
        )
    ).uuid
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid, external_id = uuid.uuid4(), uuid.uuid4()
    await create_ituser(
        itsystem=AD, external_id=str(object_guid), person=employee, user_key="TF"
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
    )
    return employee


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_function_catalog_add_and_rename(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    association_type_facet: uuid.UUID,
    tillidsrepraesentant: uuid.UUID,
) -> None:
    """A class event syncs the association types to the function catalog, and
    a renamed class keeps its Rollekatalog UUID, so the roles configured on
    the function are kept."""
    await trigger_event("class", tillidsrepraesentant)

    function = one((await test_client.get("/cache/functions")).json())
    assert function["mo_uuid"] == str(tillidsrepraesentant)
    assert function["name"] == "Tillidsrepræsentant"
    rk_uuid = function["rk_uuid"]
    assert rk_uuid is not None

    await graphql_client._testing__update_class(
        input=ClassUpdateInput(
            uuid=tillidsrepraesentant,
            user_key="Tillidsrepræsentant",
            name="Fællestillidsrepræsentant",
            facet_uuid=association_type_facet,
            validity=SEED_VALIDITY,
        )
    )
    await trigger_event("class", tillidsrepraesentant)

    function = one((await test_client.get("/cache/functions")).json())
    assert function["mo_uuid"] == str(tillidsrepraesentant)
    assert function["name"] == "Fællestillidsrepræsentant"
    assert function["rk_uuid"] == rk_uuid


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_person_association_becomes_function(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    tillidsrepraesentant: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_association: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """A person's association is synced as a function referencing the
    Rollekatalog UUID of its association type."""
    await create_org_unit(name="Root", uuid=root_uuid)
    unit = await create_org_unit(name="Unit", parent=root_uuid)
    employee = await create_person_with_sam_account(
        graphql_client, create_it_system, create_ituser
    )
    await create_association(org_unit=unit, person=employee)

    await trigger_event("class", tillidsrepraesentant)
    await trigger_event("person", employee)

    function = one((await test_client.get("/cache/functions")).json())
    user = one((await test_client.get(f"/cache/person/{employee}")).json())
    assert user["functions"] == [
        {"ouUuid": str(unit), "functionUuid": function["rk_uuid"]}
    ]


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_association_event_resolves_after_catalog_sync(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    tillidsrepraesentant: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_association: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """An association event syncs the person. An association type unknown to
    Rollekatalog is sent with a null functionUuid, which Rollekatalog skips,
    and resolves when the catalog is synced — without a person resync."""
    await create_org_unit(name="Root", uuid=root_uuid)
    unit = await create_org_unit(name="Unit", parent=root_uuid)
    employee = await create_person_with_sam_account(
        graphql_client, create_it_system, create_ituser
    )
    association = await create_association(org_unit=unit, person=employee)

    await trigger_event("association", association)

    user = one((await test_client.get(f"/cache/person/{employee}")).json())
    assert user["functions"] == [{"ouUuid": str(unit), "functionUuid": None}]

    await trigger_event("class", tillidsrepraesentant)

    function = one((await test_client.get("/cache/functions")).json())
    assert function["rk_uuid"] is not None
    user = one((await test_client.get(f"/cache/person/{employee}")).json())
    assert user["functions"] == [
        {"ouUuid": str(unit), "functionUuid": function["rk_uuid"]}
    ]


EXCLUDED = "00000000-0000-4000-0000-000000000001"


@pytest.mark.integration_test
@pytest.mark.envvar(
    {"LISTEN_TO_CHANGES_IN_MO": "False", "EXCLUDE_ORG_UNITS": f'["{EXCLUDED}"]'}
)
async def test_association_in_unsynced_org_unit_produces_no_function(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    tillidsrepraesentant: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_association: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """Associations in org units outside the sync tree or in an excluded unit
    never produce a function, so we never reference an org unit we don't
    sync."""
    await create_org_unit(name="Root", uuid=root_uuid)
    outside = await create_org_unit(name="Outside the sync tree")
    excluded = await create_org_unit(
        name="Excluded", parent=root_uuid, uuid=uuid.UUID(EXCLUDED)
    )
    kept = await create_org_unit(name="Kept", parent=root_uuid)
    employee = await create_person_with_sam_account(
        graphql_client, create_it_system, create_ituser
    )
    await create_association(org_unit=outside, person=employee)
    await create_association(org_unit=excluded, person=employee)
    await create_association(org_unit=kept, person=employee)

    await trigger_event("person", employee)

    user = one((await test_client.get(f"/cache/person/{employee}")).json())
    assert [f["ouUuid"] for f in user["functions"]] == [str(kept)]
