# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Reproduce duplicate-key spam from concurrent sync_person calls.

When a person is created in MO, several events fan out (person, ituser,
address, engagement) and each one calls sync_person on the same person
in its own transaction. They all observe an empty DB, all queue an
INSERT for the same row, and only the first commit wins — the others
fail with a duplicate-key violation on the unique extUuid.
"""

import asyncio
import uuid
from collections.abc import Awaitable
from collections.abc import Callable
from datetime import datetime
from unittest.mock import patch

import pytest
from fastramqpi.pytest_util import retry
from structlog.testing import capture_logs
from httpx import AsyncClient

from os2mo_rollekatalog import person as person_module
from os2mo_rollekatalog.autogenerated_graphql_client import EmployeeCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient
from os2mo_rollekatalog.autogenerated_graphql_client import ITUserUpdateInput
from os2mo_rollekatalog.autogenerated_graphql_client import RAValidityInput


CONCURRENT = 10


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_concurrent_sync_person_no_duplicate_key_error(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_engagement: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    await create_org_unit(name="Root", uuid=root_uuid)
    org_unit = await create_org_unit(name="OU", parent=root_uuid)

    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Concurrent", surname="User")
        )
    ).uuid

    eng = await create_engagement(org_unit=org_unit, person=employee)

    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid = uuid.uuid4()
    external_id = uuid.uuid4()
    await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="CU",
        engagements=[eng],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
        engagements=[eng],
    )

    # AMQP is disabled for this test, so the cache stays empty until our
    # POSTs run. We only need to wait for MO to be consistent enough that
    # /debug/person resolves the user.
    @retry()
    async def wait_for_mo() -> None:
        debug = (await test_client.get(f"/debug/person/{employee}")).json()
        assert isinstance(debug, list) and debug, f"MO not ready: {debug}"

    await wait_for_mo()

    # Gate every concurrent sync_person between its SELECT and its
    # INSERT/COMMIT, so all N transactions are guaranteed to have
    # observed an empty DB before any of them attempts to write.
    # Without this, asyncio.gather doesn't reliably reproduce the race
    # because one task can finish its commit before the next reads.
    #
    # The wait has a timeout so that when the production code is
    # properly serialized (by the advisory lock), the lone task at the
    # barrier proceeds after 1s, and subsequent tasks get
    # BrokenBarrierError and proceed too — no deadlock.
    barrier = asyncio.Barrier(CONCURRENT)
    real_fetch = person_module.fetch_users_from_db

    async def synchronized_fetch(session, p_uuid):
        result = await real_fetch(session, p_uuid)
        if p_uuid == employee:
            try:
                await asyncio.wait_for(barrier.wait(), timeout=1.0)
            except (asyncio.TimeoutError, asyncio.BrokenBarrierError):
                pass
        return result

    with patch(
        "os2mo_rollekatalog.person.fetch_users_from_db",
        new=synchronized_fetch,
    ), capture_logs() as cap_logs:
        responses = await asyncio.gather(
            *(test_client.post(f"/sync/person/{employee}") for _ in range(CONCURRENT)),
            return_exceptions=True,
        )

    for r in responses:
        assert not isinstance(r, BaseException), f"request raised: {r!r}"
        assert r.status_code == 200, f"request failed: {r.status_code} {r.text}"

    add_count = sum(1 for log in cap_logs if log["event"] == "Add new user")
    unchanged_count = sum(1 for log in cap_logs if log["event"] == "User unchanged")
    assert add_count == 1, f"expected exactly one Add new user, got {add_count}"
    assert (
        unchanged_count == CONCURRENT - 1
    ), f"expected {CONCURRENT - 1} User unchanged, got {unchanged_count}"

    cached = (await test_client.get(f"/cache/person/{employee}")).json()
    assert cached == [
        {
            "extUuid": str(external_id),
            "nemloginUuid": None,
            "userId": "CU",
            "name": "Concurrent User",
            "email": None,
            "positions": [
                {
                    "name": "Jurist",
                    "orgUnitUuid": str(org_unit),
                }
            ],
        }
    ]


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_sync_handles_extuuid_change_with_same_nemlogin(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
    mit_id_employee: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_engagement: Callable[..., Awaitable[uuid.UUID]],
    create_address: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """FK external_id can change for the same AD account (e.g., FK Org
    re-registration). The next sync produces a to_remove + to_add for
    the same person carrying the same nemloginUuid. Without an explicit
    flush between the loops, SQLA's INSERT-before-DELETE order trips
    the unique constraint on nemloginUuid.
    """
    await create_org_unit(name="Root", uuid=root_uuid)
    org_unit = await create_org_unit(name="OU", parent=root_uuid)
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Swap", surname="User")
        )
    ).uuid
    eng = await create_engagement(org_unit=org_unit, person=employee)

    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid = uuid.uuid4()
    fk_external_id_original = uuid.uuid4()
    fk_external_id_new = uuid.uuid4()
    mit_id = uuid.uuid4()

    ad_ituser = await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="SU",
        engagements=[eng],
    )
    fk_ituser = await create_ituser(
        itsystem=FK,
        external_id=str(fk_external_id_original),
        person=employee,
        user_key=str(object_guid),
        engagements=[eng],
    )
    await create_address(
        person=employee,
        value=str(mit_id),
        address_type=mit_id_employee,
        ituser=ad_ituser,
    )

    @retry()
    async def wait_for_mo() -> None:
        debug = (await test_client.get(f"/debug/person/{employee}")).json()
        assert isinstance(debug, list) and debug, f"MO not ready: {debug}"

    await wait_for_mo()

    # First sync — row gets created with the original FK external_id.
    response = await test_client.post(f"/sync/person/{employee}")
    assert response.status_code == 200, response.text
    cached = (await test_client.get(f"/cache/person/{employee}")).json()
    assert cached == [
        {
            "extUuid": str(fk_external_id_original),
            "nemloginUuid": str(mit_id),
            "userId": "SU",
            "name": "Swap User",
            "email": None,
            "positions": [
                {"name": "Jurist", "orgUnitUuid": str(org_unit)},
            ],
        }
    ]

    # Swap the FK ituser's external_id. AD ituser unchanged → same userId,
    # same nemloginUuid carry over, but extUuid flips.
    await graphql_client._testing__update_it_user(
        input=ITUserUpdateInput(
            uuid=fk_ituser,
            external_id=str(fk_external_id_new),
            validity=RAValidityInput(from_=datetime.now()),
        )
    )

    @retry()
    async def wait_for_swap() -> None:
        debug = (await test_client.get(f"/debug/person/{employee}")).json()
        assert debug and debug[0]["extUuid"] == str(fk_external_id_new), debug

    await wait_for_swap()

    with capture_logs() as cap_logs:
        response = await test_client.post(f"/sync/person/{employee}")
        assert response.status_code == 200, response.text

    events = [log["event"] for log in cap_logs]
    assert events.count("Remove user") == 1, events
    assert events.count("Add new user") == 1, events

    cached = (await test_client.get(f"/cache/person/{employee}")).json()
    assert cached == [
        {
            "extUuid": str(fk_external_id_new),
            "nemloginUuid": str(mit_id),
            "userId": "SU",
            "name": "Swap User",
            "email": None,
            "positions": [
                {"name": "Jurist", "orgUnitUuid": str(org_unit)},
            ],
        }
    ]


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_ituser_event_dedups_validities(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    root_uuid: uuid.UUID,
    create_org_unit: Callable[..., Awaitable[uuid.UUID]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_engagement: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """A single ituser event with many validity periods triggers exactly
    one sync_person call per unique person.

    `get_uuids_for_it_user` queries `validities(start: null, end: null)`,
    so an ituser that has been updated multiple times yields multiple
    rows — but they almost always reference the same person. Without
    dedup the handler would call sync_person once per validity row,
    producing duplicate work and noisy logs (see the "User unchanged"
    spam reported in #70184). The handler must collapse the rows by
    person UUID before dispatching.
    """
    await create_org_unit(name="Root", uuid=root_uuid)
    org_unit = await create_org_unit(name="OU", parent=root_uuid)
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Many", surname="Validities")
        )
    ).uuid
    eng = await create_engagement(org_unit=org_unit, person=employee)

    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid = uuid.uuid4()
    external_id = uuid.uuid4()

    ad_ituser = await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="MV",
        engagements=[eng],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
        engagements=[eng],
    )

    # Bump the ituser repeatedly so it accumulates many validity rows.
    # MO collapses validities when nothing changes, so vary user_key each
    # round to force a new validity row per call.
    from datetime import datetime, timedelta

    for day in range(1, 6):
        await graphql_client._testing__update_it_user(
            input=ITUserUpdateInput(
                uuid=ad_ituser,
                user_key=f"MV-{day}",
                validity=RAValidityInput(from_=datetime.now() + timedelta(days=day)),
            )
        )

    @retry()
    async def wait_for_validities() -> None:
        result = await graphql_client.get_uuids_for_it_user(ad_ituser)
        validities = [v for obj in result.objects for v in obj.validities]
        assert len(validities) >= 5, f"only {len(validities)} validities"

    await wait_for_validities()

    with patch("os2mo_rollekatalog.events.sync_person") as mock_sync:
        response = await test_client.post(
            "/ituser",
            json={"subject": str(ad_ituser), "priority": 10000},
        )
        assert response.status_code == 200, response.text

    # Exactly one sync_person call, for our employee — not one per validity.
    # sync_person(mo, periodic_sync, session, ad_key, fk_key, email_key,
    # mit_id_key, root_org_unit, person_uuid, ...) → person_uuid is positional 8.
    person_uuids = {call.args[8] for call in mock_sync.call_args_list}
    assert person_uuids == {employee}, person_uuids
    assert mock_sync.call_count == 1, mock_sync.call_args_list
