# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Which AD itsystem each user account came from, deciding its Rollekatalog
domain."""

import uuid
from collections.abc import Awaitable
from collections.abc import Callable

import pytest
from httpx import AsyncClient

from os2mo_rollekatalog.autogenerated_graphql_client import EmployeeCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient


@pytest.mark.integration_test
@pytest.mark.envvar(
    {"LISTEN_TO_CHANGES_IN_MO": "False", "ITSYSTEM_DOMAINS": '{"Skole-AD": "Skole"}'}
)
async def test_user_records_which_ad_itsystem_it_came_from(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """A person with an account in each AD gets one user per account, each
    recording its AD itsystem — the fact that decides which Rollekatalog
    domain the user is uploaded to."""
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Skole", surname="Lærer")
        )
    ).uuid
    AD = await create_it_system("Active Directory")
    SKOLE_AD = await create_it_system("Skole-AD")
    FK = await create_it_system("FK ORG")

    ad_guid, ad_external = uuid.uuid4(), uuid.uuid4()
    await create_ituser(
        itsystem=AD, external_id=str(ad_guid), person=employee, user_key="SL"
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(ad_external),
        person=employee,
        user_key=str(ad_guid),
    )
    skole_guid, skole_external = uuid.uuid4(), uuid.uuid4()
    await create_ituser(
        itsystem=SKOLE_AD,
        external_id=str(skole_guid),
        person=employee,
        user_key="SL-skole",
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(skole_external),
        person=employee,
        user_key=str(skole_guid),
    )

    await trigger_event("person", employee)

    users = (await test_client.get(f"/cache/person/{employee}")).json()
    assert sorted(users, key=lambda u: u["userId"]) == [
        {
            "extUuid": str(ad_external),
            "nemloginUuid": None,
            "userId": "SL",
            "name": "Skole Lærer",
            "email": None,
            "positions": [],
            "itsystem_user_key": "Active Directory",
        },
        {
            "extUuid": str(skole_external),
            "nemloginUuid": None,
            "userId": "SL-skole",
            "name": "Skole Lærer",
            "email": None,
            "positions": [],
            "itsystem_user_key": "Skole-AD",
        },
    ]
