# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Which email a synced user gets."""

import uuid
from collections.abc import Awaitable
from collections.abc import Callable
from datetime import datetime
from datetime import timedelta

import pytest
from httpx import AsyncClient
from more_itertools import one

from os2mo_rollekatalog.autogenerated_graphql_client import AddressUpdateInput
from os2mo_rollekatalog.autogenerated_graphql_client import EmployeeCreateInput
from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient
from os2mo_rollekatalog.autogenerated_graphql_client import RAValidityInput


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_email_linked_to_ituser_goes_to_that_account(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    email_employee: uuid.UUID,
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_address: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """An email linked to an ituser is only used for that account."""
    # Arrange: a person with two AD accounts, and an email linked to one.
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Anders", surname="And")
        )
    ).uuid
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    linked_guid, linked_external = uuid.uuid4(), uuid.uuid4()
    other_guid, other_external = uuid.uuid4(), uuid.uuid4()
    linked_ituser = await create_ituser(
        itsystem=AD,
        external_id=str(linked_guid),
        person=employee,
        user_key="LINKED",
        engagements=[],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(linked_external),
        person=employee,
        user_key=str(linked_guid),
        engagements=[],
    )
    await create_ituser(
        itsystem=AD,
        external_id=str(other_guid),
        person=employee,
        user_key="OTHER",
        engagements=[],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(other_external),
        person=employee,
        user_key=str(other_guid),
        engagements=[],
    )
    await create_address(
        person=employee,
        value="linked@example.org",
        address_type=email_employee,
        ituser=linked_ituser,
    )

    # Act.
    await trigger_event("person", employee)

    # Assert: only the linked account gets the email.
    users = (await test_client.get(f"/cache/person/{employee}")).json()
    email_by_user = {user["userId"]: user["email"] for user in users}
    assert email_by_user == {"LINKED": "linked@example.org", "OTHER": None}


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_unlinked_email_is_used_for_any_account(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    email_employee: uuid.UUID,
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_address: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """An email with no ituser link is used as a fallback (linking an
    address to an ituser is optional in MO)."""
    # Arrange: a person with one AD account and an unlinked email.
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Joakim", surname="von And")
        )
    ).uuid
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid, external_id = uuid.uuid4(), uuid.uuid4()
    await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="JvA",
        engagements=[],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
        engagements=[],
    )
    await create_address(
        person=employee, value="unlinked@example.org", address_type=email_employee
    )

    # Act.
    await trigger_event("person", employee)

    # Assert.
    user = one((await test_client.get(f"/cache/person/{employee}")).json())
    assert user["email"] == "unlinked@example.org"


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_current_email_preferred_over_future(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    email_employee: uuid.UUID,
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_address: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """With one address valid now and one only valid in the future, the
    current one is used."""
    # Arrange: a person with one AD account and two linked emails, one of
    # which only becomes valid in a year.
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Andersine", surname="And")
        )
    ).uuid
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid, external_id = uuid.uuid4(), uuid.uuid4()
    ituser = await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="AsA",
        engagements=[],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
        engagements=[],
    )
    await create_address(
        person=employee,
        value="future@example.org",
        address_type=email_employee,
        ituser=ituser,
        from_=datetime.now() + timedelta(days=365),
    )
    await create_address(
        person=employee,
        value="current@example.org",
        address_type=email_employee,
        ituser=ituser,
    )

    # Act.
    await trigger_event("person", employee)

    # Assert.
    user = one((await test_client.get(f"/cache/person/{employee}")).json())
    assert user["email"] == "current@example.org"


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_newest_email_wins_among_multiple_current(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event: Callable[[str, uuid.UUID], Awaitable[None]],
    root_uuid: uuid.UUID,
    email_employee: uuid.UUID,
    create_it_system: Callable[..., Awaitable[uuid.UUID]],
    create_ituser: Callable[..., Awaitable[uuid.UUID]],
    create_address: Callable[..., Awaitable[uuid.UUID]],
) -> None:
    """With several currently valid addresses, the newest one is used — the
    one whose validity starts latest — not the most recently edited."""
    # Arrange: two linked emails, both valid now. The seed-dated one is edited
    # recently (its current version then starts after the 2020 one). Newest
    # created first so query order cannot accidentally satisfy the assert.
    employee = (
        await graphql_client._testing__create_employee(
            input=EmployeeCreateInput(given_name="Georg", surname="Gearløs")
        )
    ).uuid
    AD = await create_it_system("Active Directory")
    FK = await create_it_system("FK ORG")
    object_guid, external_id = uuid.uuid4(), uuid.uuid4()
    ituser = await create_ituser(
        itsystem=AD,
        external_id=str(object_guid),
        person=employee,
        user_key="GG",
        engagements=[],
    )
    await create_ituser(
        itsystem=FK,
        external_id=str(external_id),
        person=employee,
        user_key=str(object_guid),
        engagements=[],
    )
    await create_address(
        person=employee,
        value="newest@example.org",
        address_type=email_employee,
        ituser=ituser,
        from_=datetime(2020, 1, 1),
    )
    oldest = await create_address(
        person=employee,
        value="oldest@example.org",
        address_type=email_employee,
        ituser=ituser,
    )
    await graphql_client._testing__update_address(
        input=AddressUpdateInput(
            uuid=oldest,
            person=employee,
            value="oldest-edited@example.org",
            address_type=email_employee,
            ituser=ituser,
            validity=RAValidityInput(from_=datetime(2026, 1, 1)),
        )
    )

    # Act.
    await trigger_event("person", employee)

    # Assert.
    user = one((await test_client.get(f"/cache/person/{employee}")).json())
    assert user["email"] == "newest@example.org"
