# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
"""Org units in EXCLUDE_ORG_UNITS (and their descendants) are not synced, and
never produce person positions."""

import uuid

import pytest
from httpx import AsyncClient

from os2mo_rollekatalog.autogenerated_graphql_client import GraphQLClient

EXCLUDED = "00000000-0000-4000-0000-000000000001"


@pytest.mark.integration_test
@pytest.mark.envvar(
    {"LISTEN_TO_CHANGES_IN_MO": "False", "EXCLUDE_ORG_UNITS": f'["{EXCLUDED}"]'}
)
async def test_excluded_org_unit_and_descendants_are_not_synced(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event,
    root_uuid: uuid.UUID,
    org_unit_type: uuid.UUID,
) -> None:
    """The excluded unit and its descendants are not synced, while a sibling
    outside the excluded subtree still is."""
    # Arrange: root with an excluded unit + a child under it, and a kept sibling.
    await graphql_client._testing__create_org_unit_root(
        root_uuid=root_uuid, name="Root", org_unit_type=org_unit_type
    )
    excluded = (
        await graphql_client._testing__create_org_unit(
            name="Excluded",
            parent=root_uuid,
            org_unit_type=org_unit_type,
            uuid=uuid.UUID(EXCLUDED),
        )
    ).uuid
    excluded_child = (
        await graphql_client._testing__create_org_unit(
            name="Excluded child", parent=excluded, org_unit_type=org_unit_type
        )
    ).uuid
    kept = (
        await graphql_client._testing__create_org_unit(
            name="Kept", parent=root_uuid, org_unit_type=org_unit_type
        )
    ).uuid

    # Act: sync all three.
    for org_unit in (excluded, excluded_child, kept):
        await trigger_event("org_unit", org_unit)

    # Assert: the excluded subtree is absent from the cache; the sibling is present.
    assert (await test_client.get(f"/cache/org_unit/{excluded}")).json() is None
    assert (await test_client.get(f"/cache/org_unit/{excluded_child}")).json() is None
    assert (await test_client.get(f"/cache/org_unit/{kept}")).json() == {
        "uuid": str(kept),
        "name": "Kept",
        "parentOrgUnitUuid": str(root_uuid),
        "manager": None,
        "klePerforming": [],
        "kleInterest": [],
    }


@pytest.mark.integration_test
@pytest.mark.envvar(
    {"LISTEN_TO_CHANGES_IN_MO": "False", "EXCLUDE_ORG_UNITS": f'["{EXCLUDED}"]'}
)
async def test_person_keeps_only_positions_in_kept_units(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event,
    root_uuid: uuid.UUID,
    org_unit_type: uuid.UUID,
    engagement_type: uuid.UUID,
    job_function: uuid.UUID,
) -> None:
    """A person with engagements in both an excluded and a kept unit is synced
    with only the position in the kept unit."""
    # Arrange: an excluded unit and a kept unit.
    await graphql_client._testing__create_org_unit_root(
        root_uuid=root_uuid, name="Root", org_unit_type=org_unit_type
    )
    excluded = (
        await graphql_client._testing__create_org_unit(
            name="Excluded",
            parent=root_uuid,
            org_unit_type=org_unit_type,
            uuid=uuid.UUID(EXCLUDED),
        )
    ).uuid
    kept = (
        await graphql_client._testing__create_org_unit(
            name="Kept", parent=root_uuid, org_unit_type=org_unit_type
        )
    ).uuid
    # ... and a person with an engagement in each.
    employee = (
        await graphql_client._testing__create_employee(
            first_name="Anders", last_name="And"
        )
    ).uuid
    eng_excluded = (
        await graphql_client._testing__create_engagement(
            excluded, employee, engagement_type, job_function
        )
    ).uuid
    eng_kept = (
        await graphql_client._testing__create_engagement(
            kept, employee, engagement_type, job_function
        )
    ).uuid
    # A matching AD + FK-org ituser pair (linked by external_id) makes the person
    # a syncable Rollekatalog user.
    AD = (await graphql_client._testing__create_it_system("Active Directory")).uuid
    FK = (await graphql_client._testing__create_it_system("FK ORG")).uuid
    object_guid = uuid.uuid4()
    external_id = uuid.uuid4()
    await graphql_client._testing__create_it_user(
        AD, str(object_guid), employee, "AA", None, [eng_excluded, eng_kept]
    )
    await graphql_client._testing__create_it_user(
        FK, str(external_id), employee, str(object_guid), None, [eng_excluded, eng_kept]
    )

    # Act.
    await trigger_event("person", employee)

    # Assert: only the kept unit's position survives.
    assert (await test_client.get(f"/cache/person/{employee}")).json() == [
        {
            "extUuid": str(external_id),
            "nemloginUuid": None,
            "userId": "AA",
            "name": "Anders And",
            "email": None,
            "positions": [{"name": "Jurist", "orgUnitUuid": str(kept)}],
        }
    ]


@pytest.mark.integration_test
@pytest.mark.envvar(
    {"LISTEN_TO_CHANGES_IN_MO": "False", "EXCLUDE_ORG_UNITS": f'["{EXCLUDED}"]'}
)
async def test_person_with_only_excluded_engagements_is_not_synced(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event,
    root_uuid: uuid.UUID,
    org_unit_type: uuid.UUID,
    engagement_type: uuid.UUID,
    job_function: uuid.UUID,
) -> None:
    """A person whose only engagement is in an excluded unit is not synced.

    Contrast with test_user_without_engagements_is_kept: having engagements that
    all resolve to excluded units drops the user, but having no engagements at
    all does not (#70811)."""
    # Arrange: only an excluded unit, and a person with an engagement there.
    await graphql_client._testing__create_org_unit_root(
        root_uuid=root_uuid, name="Root", org_unit_type=org_unit_type
    )
    excluded = (
        await graphql_client._testing__create_org_unit(
            name="Excluded",
            parent=root_uuid,
            org_unit_type=org_unit_type,
            uuid=uuid.UUID(EXCLUDED),
        )
    ).uuid
    employee = (
        await graphql_client._testing__create_employee(
            first_name="Fedt", last_name="mule"
        )
    ).uuid
    eng = (
        await graphql_client._testing__create_engagement(
            excluded, employee, engagement_type, job_function
        )
    ).uuid
    AD = (await graphql_client._testing__create_it_system("Active Directory")).uuid
    FK = (await graphql_client._testing__create_it_system("FK ORG")).uuid
    object_guid = uuid.uuid4()
    external_id = uuid.uuid4()
    await graphql_client._testing__create_it_user(
        AD, str(object_guid), employee, "FM", None, [eng]
    )
    await graphql_client._testing__create_it_user(
        FK, str(external_id), employee, str(object_guid), None, [eng]
    )

    # Act.
    await trigger_event("person", employee)

    # Assert: the person is not in the cache.
    assert (await test_client.get(f"/cache/person/{employee}")).json() == []


@pytest.mark.integration_test
@pytest.mark.envvar({"LISTEN_TO_CHANGES_IN_MO": "False"})
async def test_user_without_engagements_is_kept(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    trigger_event,
    root_uuid: uuid.UUID,
) -> None:
    """A user with no engagements at all is still synced (with no positions).

    The exclusion drop-rule only drops users whose engagements *all* resolve to
    excluded units; a user that simply has no engagements must not be dropped
    (#70811)."""
    # Arrange: a person with an AD + FK-org ituser pair but no engagements.
    employee = (
        await graphql_client._testing__create_employee(
            first_name="Joakim", last_name="von And"
        )
    ).uuid
    AD = (await graphql_client._testing__create_it_system("Active Directory")).uuid
    FK = (await graphql_client._testing__create_it_system("FK ORG")).uuid
    object_guid = uuid.uuid4()
    external_id = uuid.uuid4()
    await graphql_client._testing__create_it_user(
        AD, str(object_guid), employee, "JvA", None, []
    )
    await graphql_client._testing__create_it_user(
        FK, str(external_id), employee, str(object_guid), None, []
    )

    # Act.
    await trigger_event("person", employee)

    # Assert: the user is synced with an empty positions list.
    assert (await test_client.get(f"/cache/person/{employee}")).json() == [
        {
            "extUuid": str(external_id),
            "nemloginUuid": None,
            "userId": "JvA",
            "name": "Joakim von And",
            "email": None,
            "positions": [],
        }
    ]
