# Generated by ariadne-codegen on 2025-03-10 11:56
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class TestingRenameOrgUnit(BaseModel):
    org_unit_update: "TestingRenameOrgUnitOrgUnitUpdate"


class TestingRenameOrgUnitOrgUnitUpdate(BaseModel):
    uuid: UUID


TestingRenameOrgUnit.update_forward_refs()
TestingRenameOrgUnitOrgUnitUpdate.update_forward_refs()
