# Generated by ariadne-codegen on 2024-06-20 14:00
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class TestingMoveOrgUnit(BaseModel):
    org_unit_update: "TestingMoveOrgUnitOrgUnitUpdate"


class TestingMoveOrgUnitOrgUnitUpdate(BaseModel):
    uuid: UUID


TestingMoveOrgUnit.update_forward_refs()
TestingMoveOrgUnitOrgUnitUpdate.update_forward_refs()
