# Generated by ariadne-codegen on 2025-03-06 13:15
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class TestingMoveOrgUnitToRoot(BaseModel):
    org_unit_update: "TestingMoveOrgUnitToRootOrgUnitUpdate"


class TestingMoveOrgUnitToRootOrgUnitUpdate(BaseModel):
    uuid: UUID


TestingMoveOrgUnitToRoot.update_forward_refs()
TestingMoveOrgUnitToRootOrgUnitUpdate.update_forward_refs()
