# Generated by ariadne-codegen on 2025-03-10 13:03
# Source: queries.graphql

from typing import List, Optional
from uuid import UUID

from .base_model import BaseModel


class TestingGetJobFunction(BaseModel):
    facets: "TestingGetJobFunctionFacets"


class TestingGetJobFunctionFacets(BaseModel):
    objects: List["TestingGetJobFunctionFacetsObjects"]


class TestingGetJobFunctionFacetsObjects(BaseModel):
    current: Optional["TestingGetJobFunctionFacetsObjectsCurrent"]


class TestingGetJobFunctionFacetsObjectsCurrent(BaseModel):
    classes: List["TestingGetJobFunctionFacetsObjectsCurrentClasses"]


class TestingGetJobFunctionFacetsObjectsCurrentClasses(BaseModel):
    uuid: UUID
    user_key: str


TestingGetJobFunction.update_forward_refs()
TestingGetJobFunctionFacets.update_forward_refs()
TestingGetJobFunctionFacetsObjects.update_forward_refs()
TestingGetJobFunctionFacetsObjectsCurrent.update_forward_refs()
TestingGetJobFunctionFacetsObjectsCurrentClasses.update_forward_refs()
