# Generated by ariadne-codegen on 2025-03-10 11:56
# Source: queries.graphql

from typing import List, Optional
from uuid import UUID

from .base_model import BaseModel


class GetOrgUnit(BaseModel):
    org_units: "GetOrgUnitOrgUnits"
    managers: "GetOrgUnitManagers"
    kles: "GetOrgUnitKles"


class GetOrgUnitOrgUnits(BaseModel):
    objects: List["GetOrgUnitOrgUnitsObjects"]


class GetOrgUnitOrgUnitsObjects(BaseModel):
    current: Optional["GetOrgUnitOrgUnitsObjectsCurrent"]


class GetOrgUnitOrgUnitsObjectsCurrent(BaseModel):
    uuid: UUID
    name: str
    parent: Optional["GetOrgUnitOrgUnitsObjectsCurrentParent"]
    ancestors: List["GetOrgUnitOrgUnitsObjectsCurrentAncestors"]


class GetOrgUnitOrgUnitsObjectsCurrentParent(BaseModel):
    uuid: UUID


class GetOrgUnitOrgUnitsObjectsCurrentAncestors(BaseModel):
    uuid: UUID


class GetOrgUnitManagers(BaseModel):
    objects: List["GetOrgUnitManagersObjects"]


class GetOrgUnitManagersObjects(BaseModel):
    validities: List["GetOrgUnitManagersObjectsValidities"]


class GetOrgUnitManagersObjectsValidities(BaseModel):
    person: Optional[List["GetOrgUnitManagersObjectsValiditiesPerson"]]


class GetOrgUnitManagersObjectsValiditiesPerson(BaseModel):
    uuid: UUID
    itusers: List["GetOrgUnitManagersObjectsValiditiesPersonItusers"]


class GetOrgUnitManagersObjectsValiditiesPersonItusers(BaseModel):
    user_key: str


class GetOrgUnitKles(BaseModel):
    objects: List["GetOrgUnitKlesObjects"]


class GetOrgUnitKlesObjects(BaseModel):
    validities: List["GetOrgUnitKlesObjectsValidities"]


class GetOrgUnitKlesObjectsValidities(BaseModel):
    kle_number: "GetOrgUnitKlesObjectsValiditiesKleNumber"
    kle_aspects: List["GetOrgUnitKlesObjectsValiditiesKleAspects"]


class GetOrgUnitKlesObjectsValiditiesKleNumber(BaseModel):
    user_key: str


class GetOrgUnitKlesObjectsValiditiesKleAspects(BaseModel):
    scope: Optional[str]


GetOrgUnit.update_forward_refs()
GetOrgUnitOrgUnits.update_forward_refs()
GetOrgUnitOrgUnitsObjects.update_forward_refs()
GetOrgUnitOrgUnitsObjectsCurrent.update_forward_refs()
GetOrgUnitOrgUnitsObjectsCurrentParent.update_forward_refs()
GetOrgUnitOrgUnitsObjectsCurrentAncestors.update_forward_refs()
GetOrgUnitManagers.update_forward_refs()
GetOrgUnitManagersObjects.update_forward_refs()
GetOrgUnitManagersObjectsValidities.update_forward_refs()
GetOrgUnitManagersObjectsValiditiesPerson.update_forward_refs()
GetOrgUnitManagersObjectsValiditiesPersonItusers.update_forward_refs()
GetOrgUnitKles.update_forward_refs()
GetOrgUnitKlesObjects.update_forward_refs()
GetOrgUnitKlesObjectsValidities.update_forward_refs()
GetOrgUnitKlesObjectsValiditiesKleNumber.update_forward_refs()
GetOrgUnitKlesObjectsValiditiesKleAspects.update_forward_refs()
