# Generated by ariadne-codegen on 2025-03-10 13:03
# Source: queries.graphql

from typing import List, Optional
from uuid import UUID

from .base_model import BaseModel


class GetPersonUuidForAddress(BaseModel):
    addresses: "GetPersonUuidForAddressAddresses"


class GetPersonUuidForAddressAddresses(BaseModel):
    objects: List["GetPersonUuidForAddressAddressesObjects"]


class GetPersonUuidForAddressAddressesObjects(BaseModel):
    validities: List["GetPersonUuidForAddressAddressesObjectsValidities"]


class GetPersonUuidForAddressAddressesObjectsValidities(BaseModel):
    employee_uuid: Optional[UUID]


GetPersonUuidForAddress.update_forward_refs()
GetPersonUuidForAddressAddresses.update_forward_refs()
GetPersonUuidForAddressAddressesObjects.update_forward_refs()
GetPersonUuidForAddressAddressesObjectsValidities.update_forward_refs()
