# Generated by ariadne-codegen on 2024-06-11 11:37
# Source: queries.graphql

from typing import List, Optional
from uuid import UUID

from .base_model import BaseModel


class GetPersonUuidForItUser(BaseModel):
    itusers: "GetPersonUuidForItUserItusers"


class GetPersonUuidForItUserItusers(BaseModel):
    objects: List["GetPersonUuidForItUserItusersObjects"]


class GetPersonUuidForItUserItusersObjects(BaseModel):
    validities: List["GetPersonUuidForItUserItusersObjectsValidities"]


class GetPersonUuidForItUserItusersObjectsValidities(BaseModel):
    employee_uuid: Optional[UUID]


GetPersonUuidForItUser.update_forward_refs()
GetPersonUuidForItUserItusers.update_forward_refs()
GetPersonUuidForItUserItusersObjects.update_forward_refs()
GetPersonUuidForItUserItusersObjectsValidities.update_forward_refs()
