# Generated by ariadne-codegen on 2025-09-01 14:03
# Source: queries.graphql

from typing import List
from uuid import UUID

from .base_model import BaseModel


class GetPersonUuidForEngagement(BaseModel):
    engagements: "GetPersonUuidForEngagementEngagements"


class GetPersonUuidForEngagementEngagements(BaseModel):
    objects: List["GetPersonUuidForEngagementEngagementsObjects"]


class GetPersonUuidForEngagementEngagementsObjects(BaseModel):
    validities: List["GetPersonUuidForEngagementEngagementsObjectsValidities"]


class GetPersonUuidForEngagementEngagementsObjectsValidities(BaseModel):
    employee_uuid: UUID


GetPersonUuidForEngagement.update_forward_refs()
GetPersonUuidForEngagementEngagements.update_forward_refs()
GetPersonUuidForEngagementEngagementsObjects.update_forward_refs()
GetPersonUuidForEngagementEngagementsObjectsValidities.update_forward_refs()
