# Generated by ariadne-codegen on 2025-09-04 16:12
# Source: queries.graphql

from typing import List, Optional
from uuid import UUID

from .base_model import BaseModel


class GetOrgUnit(BaseModel):
    org_units: "GetOrgUnitOrgUnits"


class GetOrgUnitOrgUnits(BaseModel):
    objects: List["GetOrgUnitOrgUnitsObjects"]


class GetOrgUnitOrgUnitsObjects(BaseModel):
    current: Optional["GetOrgUnitOrgUnitsObjectsCurrent"]


class GetOrgUnitOrgUnitsObjectsCurrent(BaseModel):
    uuid: UUID
    name: str
    parent: Optional["GetOrgUnitOrgUnitsObjectsCurrentParent"]
    managers: List["GetOrgUnitOrgUnitsObjectsCurrentManagers"]
    kles: List["GetOrgUnitOrgUnitsObjectsCurrentKles"]


class GetOrgUnitOrgUnitsObjectsCurrentParent(BaseModel):
    uuid: UUID


class GetOrgUnitOrgUnitsObjectsCurrentManagers(BaseModel):
    person: Optional[List["GetOrgUnitOrgUnitsObjectsCurrentManagersPerson"]]


class GetOrgUnitOrgUnitsObjectsCurrentManagersPerson(BaseModel):
    uuid: UUID
    itusers: List["GetOrgUnitOrgUnitsObjectsCurrentManagersPersonItusers"]


class GetOrgUnitOrgUnitsObjectsCurrentManagersPersonItusers(BaseModel):
    user_key: str


class GetOrgUnitOrgUnitsObjectsCurrentKles(BaseModel):
    kle_number: List["GetOrgUnitOrgUnitsObjectsCurrentKlesKleNumber"]
    kle_aspects: List["GetOrgUnitOrgUnitsObjectsCurrentKlesKleAspects"]


class GetOrgUnitOrgUnitsObjectsCurrentKlesKleNumber(BaseModel):
    user_key: str


class GetOrgUnitOrgUnitsObjectsCurrentKlesKleAspects(BaseModel):
    scope: Optional[str]


GetOrgUnit.update_forward_refs()
GetOrgUnitOrgUnits.update_forward_refs()
GetOrgUnitOrgUnitsObjects.update_forward_refs()
GetOrgUnitOrgUnitsObjectsCurrent.update_forward_refs()
GetOrgUnitOrgUnitsObjectsCurrentParent.update_forward_refs()
GetOrgUnitOrgUnitsObjectsCurrentManagers.update_forward_refs()
GetOrgUnitOrgUnitsObjectsCurrentManagersPerson.update_forward_refs()
GetOrgUnitOrgUnitsObjectsCurrentManagersPersonItusers.update_forward_refs()
GetOrgUnitOrgUnitsObjectsCurrentKles.update_forward_refs()
GetOrgUnitOrgUnitsObjectsCurrentKlesKleNumber.update_forward_refs()
GetOrgUnitOrgUnitsObjectsCurrentKlesKleAspects.update_forward_refs()
