# Generated by ariadne-codegen on 2024-05-13 13:21
# Source: queries.graphql

from typing import Optional

from .base_model import BaseModel


class MyQuery(BaseModel):
    version: "MyQueryVersion"


class MyQueryVersion(BaseModel):
    mo_version: Optional[str]


MyQuery.update_forward_refs()
MyQueryVersion.update_forward_refs()
