#!/usr/bin/env bash

set -eo pipefail

printf "Requesting sync of Ludvigs OU\n"
syncorg=$(curl -s -X POST 'http://localhost:8000/sync/org_unit/7a8e45f7-4de0-44c8-990f-43c0565ee505')
if [ "$syncorg" != "null" ]; then
    printf "Sync OU failed. Integration returned: %s\n" "$syncorg"
    exit 1;
fi

printf "Requesting sync of Ludvig\n"
syncperson=$(curl -s -X POST 'http://localhost:8000/sync/person/4e7e5443-09a9-4a46-8cd5-f7bcefeb2902')
if [ "$syncperson" != "null" ]; then
    printf "Sync person failed. Integration returned: %s\n" "$syncperson"
    exit 1;
fi

printf "Waiting 15 seconds for sync\n"
sleep 15

printf 'Assigning "Administrator" to Ludvig in Rollekatalog\n'
curl -X PUT -H 'ApiKey: 00000000-0000-4000-0000-000000000000' 'http://localhost:8090/api/user/LudvigH/assign/userrole/1'

printf "You should now be able to log in to http://localhost:8090 with ludvig:ludvig\n"
printf "This is Ludvig in OS2mo: http://localhost:5000/employee/4e7e5443-09a9-4a46-8cd5-f7bcefeb2902#ituser\n"
